<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>R &amp; M Trade Desk</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">R &amp; M Trade Desk</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link active" href="./index.html" aria-current="page"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./mechanics.html"> 
<span class="menu-text">Strategy</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./results.html"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ablations.html"> 
<span class="menu-text">Variants</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./monitoring.html"> 
<span class="menu-text">Live Monitoring</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./limitations.html"> 
<span class="menu-text">Limitations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data_and_literature.html"> 
<span class="menu-text">Data &amp; Sources</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-strategy-in-one-sentence" id="toc-the-strategy-in-one-sentence" class="nav-link active" data-scroll-target="#the-strategy-in-one-sentence">The strategy in one sentence</a></li>
  <li><a href="#headline" id="toc-headline" class="nav-link" data-scroll-target="#headline">Headline result</a></li>
  <li><a href="#whats-behind-the-number" id="toc-whats-behind-the-number" class="nav-link" data-scroll-target="#whats-behind-the-number">What’s behind the number</a></li>
  <li><a href="#portfolio-fit" id="toc-portfolio-fit" class="nav-link" data-scroll-target="#portfolio-fit">Portfolio fit</a></li>
  <li><a href="#answering-the-two-questions-every-trading-system-writeup-needs" id="toc-answering-the-two-questions-every-trading-system-writeup-needs" class="nav-link" data-scroll-target="#answering-the-two-questions-every-trading-system-writeup-needs">Answering the two questions every trading-system writeup needs</a></li>
  <li><a href="#what-was-tested-but-not-used" id="toc-what-was-tested-but-not-used" class="nav-link" data-scroll-target="#what-was-tested-but-not-used">What was tested but not used</a></li>
  <li><a href="#future-work-treasury-management-on-undeployed-capital" id="toc-future-work-treasury-management-on-undeployed-capital" class="nav-link" data-scroll-target="#future-work-treasury-management-on-undeployed-capital">Future work: treasury management on undeployed capital</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">R &amp; M Trade Desk</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
<p class="subtitle lead">Defined-Risk Volatility-Risk-Premium Harvesting · Robert Lanni and Mario Treviño · FinTech 533 · Duke MEng FinTech</p>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-strategy-in-one-sentence" class="level2">
<h2 class="anchored" data-anchor-id="the-strategy-in-one-sentence">The strategy in one sentence</h2>
<p>A 4-instrument cross-asset put-credit-spread basket (AAPL, MSFT, WMT, GLD) with a 3-layer halt framework, sized at 16-delta short strikes with weekly Monday entries, harvesting the volatility risk premium across single-stock idiosyncratic vol and commodity-ETF cross-asset vol simultaneously.</p>
</section>
<section id="headline" class="level2">
<h2 class="anchored" data-anchor-id="headline">Headline result</h2>
<p><strong>Excess Sharpe +0.371</strong> over OOS 2018-2024, beating the single-instrument SPX put-only baseline (+0.286) by 0.085 with cross-asset diversification and 2× the trade sample.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sharpe ratio (excess of risk-free, ML overlay engaged)</strong></td>
<td style="text-align: right;"><strong>+0.371</strong></td>
</tr>
<tr class="even">
<td>Risk-free baseline (avg IRX 2018-2024)</td>
<td style="text-align: right;">2.33%</td>
</tr>
<tr class="odd">
<td><strong>Geometric mean return (GMRR, annualized)</strong></td>
<td style="text-align: right;"><strong>+2.41%</strong></td>
</tr>
<tr class="even">
<td>Annualized volatility</td>
<td style="text-align: right;">0.21%</td>
</tr>
<tr class="odd">
<td>Alpha vs SPY (annualized OLS)</td>
<td style="text-align: right;">+2.37%</td>
</tr>
<tr class="even">
<td>Beta vs SPY (OLS slope, daily)</td>
<td style="text-align: right;">+0.0014</td>
</tr>
<tr class="odd">
<td>Max drawdown over 7 years</td>
<td style="text-align: right;">-0.12%</td>
</tr>
<tr class="even">
<td>Trades total · Trades per year · Avg return per trade</td>
<td style="text-align: right;">437 · 62.8 · +8.25%</td>
</tr>
<tr class="odd">
<td><strong>DSR (PSR)</strong></td>
<td style="text-align: right;"><strong>1.0000</strong> ≥ 0.95 ✓</td>
</tr>
<tr class="even">
<td><strong>PBO via CSCV</strong></td>
<td style="text-align: right;"><strong>0.0402</strong> ≤ 0.30 ✓</td>
</tr>
</tbody>
</table>
<p>Both acceptance gates pass. See <a href="./results.html">Results</a> for the full breakdown.</p>
</section>
<section id="whats-behind-the-number" class="level2">
<h2 class="anchored" data-anchor-id="whats-behind-the-number">What’s behind the number</h2>
<ul>
<li><strong>4-instrument cross-asset basket</strong>, three single-stocks (AAPL, MSFT, WMT) for idiosyncratic short-vol exposure plus GLD for commodity-vol exposure. Selected from a 12-instrument tested universe; selection bias corrected via DSR (N̂=9 implied independent trials).</li>
<li><strong>3-layer halt framework</strong>, tail-event halts on extreme single-day market moves, drawdown gate on a trailing 90-day window, vol-regime auto-resume with a 60-day time fallback.</li>
<li><strong>Per-trade defined risk</strong>, 16-delta short put, 5-pt long-put protection, weekly Monday entries, gap-aware exit fills, VIX-conditional slippage model.</li>
<li><strong>Exogenous-factor inputs</strong>, VIX/VIX3M/VVIX/SKEW for regime classification, IRX for risk-free baseline + cash accrual, HYG-LQD spread + rolling SPY-Treasury correlation for stress detection. See <a href="./mechanics.html">Mechanics</a> for the full list.</li>
<li><strong>Honest aggregation</strong>, book Sharpe computed from the equal-weighted aggregate equity curve, not from per-instrument Sharpe averaging. Cross-instrument correlation 0.26 (low) drives the diversification benefit.</li>
</ul>
</section>
<section id="portfolio-fit" class="level2">
<h2 class="anchored" data-anchor-id="portfolio-fit">Portfolio fit</h2>
<p>This strategy is engineered as a <strong>risk-managed defensive sleeve</strong>, not a directional alpha generator. The headline profile, +2.41% annualized return, 0.21% volatility, -0.12% max drawdown across seven years including COVID, the 2022 bear, and the 2023 banking stress, is the signature of a structurally short-volatility insurance harvester rather than a stock-picking edge.</p>
<p>The natural deployment is alongside a directional alpha generator. A long-only equity factor sleeve, a momentum overlay, or a discretionary fundamental book all carry positive expected return at single-digit Sharpe with double-digit drawdown risk. Combining a directional alpha source with this defensive overlay does three things:</p>
<ul>
<li><strong>Smooths the equity curve</strong> during stress events. The defensive sleeve continued generating premium income through every named drawdown in the OOS sample, including weeks where broad-market equity exposure experienced material drawdowns.</li>
<li><strong>Releases alpha budget</strong> for higher-conviction directional bets. A portfolio manager who would otherwise hold cash to manage drawdown can instead allocate that cash to this sleeve and earn a premium on the dry powder.</li>
<li><strong>Adds a low-correlated return stream</strong>. Cross-instrument correlation inside the basket is 0.26; correlation against a broad-market directional book is materially lower because the strategy harvests the volatility premium rather than the equity premium.</li>
</ul>
<p>The 0.371 excess Sharpe is the result of a tight volatility denominator, not a large numerator. That is the design intent. A defensive sleeve should be measured by its consistency and downside containment, not by raw return magnitude. Read the +0.085 outperformance versus the SPX baseline as evidence the architecture (cross-asset basket, halt framework, ML stress overlay) compounds risk-adjusted advantage over a single-instrument baseline.</p>
</section>
<section id="answering-the-two-questions-every-trading-system-writeup-needs" class="level2">
<h2 class="anchored" data-anchor-id="answering-the-two-questions-every-trading-system-writeup-needs">Answering the two questions every trading-system writeup needs</h2>
<p>Trading-system writeups in this course are expected to answer two questions explicitly:</p>
<blockquote class="blockquote">
<p><em>How will you know your strategy is performing as expected?</em> <em>How will you quantify when the strategy stops working?</em></p>
</blockquote>
<p>Both are answered by one framework: a <strong>Hoeffding-bound live monitor</strong> that quantifies, in real time, the probability the underlying win rate has shifted away from the OOS baseline of μ = 0.730. The mechanic is straightforward: roll a 60-trade window of the realized win rate, compare it to the pre-set μ, and apply the Hoeffding inequality to get a distribution-free probability bound on whether the observed underperformance is real or random.</p>
<p>For the question <strong>how will you know it’s performing as expected</strong>: the bound stays at or above 50% (the green band) and the strategy continues at full size. Performance is plausibly within the OOS regime.</p>
<p>For the question <strong>how will you quantify when it stops working</strong>: the bound crossing below 10% is the trip-wire. At that point, observed underperformance has dropped to a probability where random chance is an implausible explanation for the gap to baseline. The threshold is dated, quantitative, distribution-free, and pre-set before live deployment.</p>
<p>Backtested over the full 1,760 OOS trading days, the bound stayed at or above 50% on 88% of post-warmup trades and registered no critical signal across the 7-year window. The full framework, threshold table, worked example, and chart are on the <a href="./monitoring.html">Live Monitoring</a> page.</p>
</section>
<section id="what-was-tested-but-not-used" class="level2">
<h2 class="anchored" data-anchor-id="what-was-tested-but-not-used">What was tested but not used</h2>
<p>The headline is one of six configurations tested. The other five (SPX-only put-credit-spread, 3-ETF basket, full 6-instrument book, and iron condor variants on the 3-instrument cluster and SPX-only) underperformed the SPX baseline. They are reported transparently on the <a href="./ablations.html">Variants</a> page; the iron-condor variant is particularly informative because adding the call wing systematically lost in the 2018-2024 trending-equity regime.</p>
</section>
<section id="future-work-treasury-management-on-undeployed-capital" class="level2">
<h2 class="anchored" data-anchor-id="future-work-treasury-management-on-undeployed-capital">Future work: treasury management on undeployed capital</h2>
<p>The current backtest accrues idle cash at the realized 13-week T-bill yield (IRX averaged 2.33% over OOS). This is the conservative baseline. A natural next step is active treasury management on the undeployed $200,000 of basket capital that backs the options positions.</p>
<p>Replacing the passive T-bill accrual with an ultra-short Treasury ETF (SGOV, BIL) or a short-duration corporate bond fund (VCSH, BSV) targets an additional 100-200 bps of carry with minimal duration or credit risk. The trade-off is a small increase in drawdown sensitivity during credit-spread blowouts, but the headline -0.12% maximum drawdown leaves substantial room before this becomes a constraint.</p>
<p>The deliberate exclusion is broad-equity exposure (SPY, QQQ) for the undeployed capital. Adding equity beta to the cash sleeve introduces correlation risk: in the stress events the strategy is designed to absorb (Volmageddon, COVID, 2022 bear, 2023 banking), the put-credit-spread portfolio is under maximum pressure exactly when an equity cash sleeve would also be drawing down. This double-correlation would destroy the maximum-drawdown profile that makes the strategy useful as a portfolio defensive sleeve.</p>
<p>Recommended treasury overlay for production deployment: 80% allocation to SGOV (0-3M Treasuries, near-zero duration, currently yielding ~5%) and 20% to short-investment-grade-corporate (VCSH, ~1y duration, currently yielding ~5%). Expected blended carry roughly 100-150 bps above passive IRX accrual, raising the strategy’s annualized return from 2.41% to approximately 3.5-4%, while keeping the maximum-drawdown floor near -0.12%. This is a low-risk capital-efficiency improvement, not a return-chasing one.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp("https:\/\/rmtradedesk\.solutions");
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "R &amp; M Trade Desk"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="an">subtitle:</span><span class="co"> "Defined-Risk Volatility-Risk-Premium Harvesting · Robert Lanni and Mario Treviño · FinTech 533 · Duke MEng FinTech"</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">## The strategy in one sentence</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a>A 4-instrument cross-asset put-credit-spread basket (AAPL, MSFT, WMT, GLD) with a 3-layer halt framework, sized at 16-delta short strikes with weekly Monday entries, harvesting the volatility risk premium across single-stock idiosyncratic vol and commodity-ETF cross-asset vol simultaneously.</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="fu">## Headline result {#headline}</span></span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>**Excess Sharpe +0.371** over OOS 2018-2024, beating the single-instrument SPX put-only baseline (+0.286) by 0.085 with cross-asset diversification and 2× the trade sample.</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a>| Metric | Value |</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a>|---|---:|</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a>| **Sharpe ratio (excess of risk-free, ML overlay engaged)** | **+0.371** |</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a>| Risk-free baseline (avg IRX 2018-2024) | 2.33% |</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>| **Geometric mean return (GMRR, annualized)** | **+2.41%** |</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a>| Annualized volatility | 0.21% |</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>| Alpha vs SPY (annualized OLS) | +2.37% |</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a>| Beta vs SPY (OLS slope, daily) | +0.0014 |</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a>| Max drawdown over 7 years | -0.12% |</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a>| Trades total · Trades per year · Avg return per trade | 437 · 62.8 · +8.25% |</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a>| **DSR (PSR)** | **1.0000** ≥ 0.95 ✓ |</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a>| **PBO via CSCV** | **0.0402** ≤ 0.30 ✓ |</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>Both acceptance gates pass. See <span class="co">[</span><span class="ot">Results</span><span class="co">](results.qmd)</span> for the full breakdown.</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a><span class="fu">## What's behind the number</span></span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**4-instrument cross-asset basket**, three single-stocks (AAPL, MSFT, WMT) for idiosyncratic short-vol exposure plus GLD for commodity-vol exposure. Selected from a 12-instrument tested universe; selection bias corrected via DSR (N̂=9 implied independent trials).</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**3-layer halt framework**, tail-event halts on extreme single-day market moves, drawdown gate on a trailing 90-day window, vol-regime auto-resume with a 60-day time fallback.</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Per-trade defined risk**, 16-delta short put, 5-pt long-put protection, weekly Monday entries, gap-aware exit fills, VIX-conditional slippage model.</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Exogenous-factor inputs**, VIX/VIX3M/VVIX/SKEW for regime classification, IRX for risk-free baseline + cash accrual, HYG-LQD spread + rolling SPY-Treasury correlation for stress detection. See <span class="co">[</span><span class="ot">Mechanics</span><span class="co">](mechanics.qmd)</span> for the full list.</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Honest aggregation**, book Sharpe computed from the equal-weighted aggregate equity curve, not from per-instrument Sharpe averaging. Cross-instrument correlation 0.26 (low) drives the diversification benefit.</span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a><span class="fu">## Portfolio fit</span></span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>This strategy is engineered as a **risk-managed defensive sleeve**, not a directional alpha generator. The headline profile, +2.41% annualized return, 0.21% volatility, -0.12% max drawdown across seven years including COVID, the 2022 bear, and the 2023 banking stress, is the signature of a structurally short-volatility insurance harvester rather than a stock-picking edge.</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>The natural deployment is alongside a directional alpha generator. A long-only equity factor sleeve, a momentum overlay, or a discretionary fundamental book all carry positive expected return at single-digit Sharpe with double-digit drawdown risk. Combining a directional alpha source with this defensive overlay does three things:</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Smooths the equity curve** during stress events. The defensive sleeve continued generating premium income through every named drawdown in the OOS sample, including weeks where broad-market equity exposure experienced material drawdowns.</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Releases alpha budget** for higher-conviction directional bets. A portfolio manager who would otherwise hold cash to manage drawdown can instead allocate that cash to this sleeve and earn a premium on the dry powder.</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Adds a low-correlated return stream**. Cross-instrument correlation inside the basket is 0.26; correlation against a broad-market directional book is materially lower because the strategy harvests the volatility premium rather than the equity premium.</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>The 0.371 excess Sharpe is the result of a tight volatility denominator, not a large numerator. That is the design intent. A defensive sleeve should be measured by its consistency and downside containment, not by raw return magnitude. Read the +0.085 outperformance versus the SPX baseline as evidence the architecture (cross-asset basket, halt framework, ML stress overlay) compounds risk-adjusted advantage over a single-instrument baseline.</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a><span class="fu">## Answering the two questions every trading-system writeup needs</span></span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a>Trading-system writeups in this course are expected to answer two questions explicitly:</span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; *How will you know your strategy is performing as expected?*</span></span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a><span class="at">&gt; *How will you quantify when the strategy stops working?*</span></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>Both are answered by one framework: a **Hoeffding-bound live monitor** that quantifies, in real time, the probability the underlying win rate has shifted away from the OOS baseline of μ = 0.730. The mechanic is straightforward: roll a 60-trade window of the realized win rate, compare it to the pre-set μ, and apply the Hoeffding inequality to get a distribution-free probability bound on whether the observed underperformance is real or random.</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>For the question **how will you know it's performing as expected**: the bound stays at or above 50% (the green band) and the strategy continues at full size. Performance is plausibly within the OOS regime.</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>For the question **how will you quantify when it stops working**: the bound crossing below 10% is the trip-wire. At that point, observed underperformance has dropped to a probability where random chance is an implausible explanation for the gap to baseline. The threshold is dated, quantitative, distribution-free, and pre-set before live deployment.</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a>Backtested over the full 1,760 OOS trading days, the bound stayed at or above 50% on 88% of post-warmup trades and registered no critical signal across the 7-year window. The full framework, threshold table, worked example, and chart are on the <span class="co">[</span><span class="ot">Live Monitoring</span><span class="co">](monitoring.qmd)</span> page.</span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a><span class="fu">## What was tested but not used</span></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a>The headline is one of six configurations tested. The other five (SPX-only put-credit-spread, 3-ETF basket, full 6-instrument book, and iron condor variants on the 3-instrument cluster and SPX-only) underperformed the SPX baseline. They are reported transparently on the <span class="co">[</span><span class="ot">Variants</span><span class="co">](ablations.qmd)</span> page; the iron-condor variant is particularly informative because adding the call wing systematically lost in the 2018-2024 trending-equity regime.</span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="fu">## Future work: treasury management on undeployed capital</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a>The current backtest accrues idle cash at the realized 13-week T-bill yield (IRX averaged 2.33% over OOS). This is the conservative baseline. A natural next step is active treasury management on the undeployed $200,000 of basket capital that backs the options positions.</span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a>Replacing the passive T-bill accrual with an ultra-short Treasury ETF (SGOV, BIL) or a short-duration corporate bond fund (VCSH, BSV) targets an additional 100-200 bps of carry with minimal duration or credit risk. The trade-off is a small increase in drawdown sensitivity during credit-spread blowouts, but the headline -0.12% maximum drawdown leaves substantial room before this becomes a constraint.</span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a>The deliberate exclusion is broad-equity exposure (SPY, QQQ) for the undeployed capital. Adding equity beta to the cash sleeve introduces correlation risk: in the stress events the strategy is designed to absorb (Volmageddon, COVID, 2022 bear, 2023 banking), the put-credit-spread portfolio is under maximum pressure exactly when an equity cash sleeve would also be drawing down. This double-correlation would destroy the maximum-drawdown profile that makes the strategy useful as a portfolio defensive sleeve.</span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a>Recommended treasury overlay for production deployment: 80% allocation to SGOV (0-3M Treasuries, near-zero duration, currently yielding ~5%) and 20% to short-investment-grade-corporate (VCSH, ~1y duration, currently yielding ~5%). Expected blended carry roughly 100-150 bps above passive IRX accrual, raising the strategy's annualized return from 2.41% to approximately 3.5-4%, while keeping the maximum-drawdown floor near -0.12%. This is a low-risk capital-efficiency improvement, not a return-chasing one.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>R &amp; M Trade Desk · Robert Lanni and Mario Treviño · FinTech 533 · Duke MEng FinTech</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>