services:
  - type: web
    name: spx-vrp-strategy
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -w 1 --threads 2 -b 0.0.0.0:$PORT website.app:app
    envVars:
      - key: PYTHON_VERSION
        value: "3.11.0"
