<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Results – R &amp; M Trade Desk</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>


<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="./index.html">
    <span class="navbar-title">R &amp; M Trade Desk</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="./index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./mechanics.html"> 
<span class="menu-text">Strategy</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link active" href="./results.html" aria-current="page"> 
<span class="menu-text">Results</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./ablations.html"> 
<span class="menu-text">Variants</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./monitoring.html"> 
<span class="menu-text">Live Monitoring</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./limitations.html"> 
<span class="menu-text">Limitations</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="./data_and_literature.html"> 
<span class="menu-text">Data &amp; Sources</span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#how-to-read-this-page" id="toc-how-to-read-this-page" class="nav-link active" data-scroll-target="#how-to-read-this-page">How to read this page</a></li>
  <li><a href="#headline" id="toc-headline" class="nav-link" data-scroll-target="#headline">Headline</a>
  <ul class="collapse">
  <li><a href="#multiple-testing-validation" id="toc-multiple-testing-validation" class="nav-link" data-scroll-target="#multiple-testing-validation">Multiple-testing validation</a></li>
  <li><a href="#equity-curve" id="toc-equity-curve" class="nav-link" data-scroll-target="#equity-curve">Equity curve</a></li>
  <li><a href="#drawdown" id="toc-drawdown" class="nav-link" data-scroll-target="#drawdown">Drawdown</a></li>
  <li><a href="#per-instrument-breakdown" id="toc-per-instrument-breakdown" class="nav-link" data-scroll-target="#per-instrument-breakdown">Per-instrument breakdown</a></li>
  </ul></li>
  <li><a href="#anchor-comparison-vs-spx-baseline" id="toc-anchor-comparison-vs-spx-baseline" class="nav-link" data-scroll-target="#anchor-comparison-vs-spx-baseline">Anchor comparison vs SPX baseline</a></li>
  <li><a href="#variants-tested-alternative-baskets" id="toc-variants-tested-alternative-baskets" class="nav-link" data-scroll-target="#variants-tested-alternative-baskets">Variants tested: alternative baskets</a></li>
  <li><a href="#variants-tested-iron-condor-architecture" id="toc-variants-tested-iron-condor-architecture" class="nav-link" data-scroll-target="#variants-tested-iron-condor-architecture">Variants tested: iron condor architecture</a></li>
  <li><a href="#halts-engaged-vs-disengaged" id="toc-halts-engaged-vs-disengaged" class="nav-link" data-scroll-target="#halts-engaged-vs-disengaged">Halts engaged vs disengaged</a></li>
  <li><a href="#stress-event-behavior" id="toc-stress-event-behavior" class="nav-link" data-scroll-target="#stress-event-behavior">Stress-event behavior</a></li>
  <li><a href="#trade-fates-and-rates" id="toc-trade-fates-and-rates" class="nav-link" data-scroll-target="#trade-fates-and-rates">Trade fates and rates</a></li>
  <li><a href="#per-trade-summary-statistics" id="toc-per-trade-summary-statistics" class="nav-link" data-scroll-target="#per-trade-summary-statistics">Per-trade summary statistics</a></li>
  <li><a href="#per-instrument-breakdown-1" id="toc-per-instrument-breakdown-1" class="nav-link" data-scroll-target="#per-instrument-breakdown-1">Per-instrument breakdown</a></li>
  <li><a href="#pl-per-trade-across-oos" id="toc-pl-per-trade-across-oos" class="nav-link" data-scroll-target="#pl-per-trade-across-oos">P&amp;L per trade across OOS</a></li>
  <li><a href="#trade-return-distribution" id="toc-trade-return-distribution" class="nav-link" data-scroll-target="#trade-return-distribution">Trade-return distribution</a></li>
  <li><a href="#ledger-monthly-pl-sample" id="toc-ledger-monthly-pl-sample" class="nav-link" data-scroll-target="#ledger-monthly-pl-sample">Ledger (monthly P&amp;L sample)</a></li>
  <li><a href="#blotter" id="toc-blotter" class="nav-link" data-scroll-target="#blotter">Blotter</a></li>
  <li><a href="#how-will-you-know-the-strategy-is-performing-as-expected" id="toc-how-will-you-know-the-strategy-is-performing-as-expected" class="nav-link" data-scroll-target="#how-will-you-know-the-strategy-is-performing-as-expected">How will you know the strategy is performing as expected?</a></li>
  <li><a href="#how-will-you-quantify-when-the-strategy-stops-working" id="toc-how-will-you-quantify-when-the-strategy-stops-working" class="nav-link" data-scroll-target="#how-will-you-quantify-when-the-strategy-stops-working">How will you quantify when the strategy stops working?</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title">Results</h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="how-to-read-this-page" class="level2">
<h2 class="anchored" data-anchor-id="how-to-read-this-page">How to read this page</h2>
<p>Sharpe ratios on this page are reported in two complementary forms:</p>
<ul>
<li><strong>Sharpe (excess)</strong>, the headline. <code>(annualized return − annualized risk-free) / annualized volatility</code>.</li>
<li><strong>Deflated Sharpe (DSR)</strong>, corrects for selection bias when many baskets are tested. Uses an implied-independent-trials count rather than the raw trial count, since adjacent baskets share underlying-instrument exposure and inflate the apparent number of independent searches.</li>
</ul>
<p>Other reported metrics:</p>
<ul>
<li><strong>PBO</strong> (Probability of Backtest Overfitting) via CSCV, the probability that the in-sample-best basket underperforms in OOS, computed by leave-out partitioning the per-instrument return matrix.</li>
<li><strong>n_trades</strong> and <strong>win rate</strong> per instrument.</li>
<li><strong>Max drawdown</strong> (signed, negative) and <strong>annualized return</strong> (geometric).</li>
</ul>
<p><strong>Risk-free rate:</strong> The risk-free is the CBOE 13-week T-bill yield (IRX), averaged over the OOS window 2018-2024 = <strong>2.33% annualized</strong>. Excess Sharpe = (annualized return − 2.33%) / annualized volatility. The risk-free reflects the actual realized T-bill yield over the test period (which included near-zero rates 2018-2021 and 4-5% rates 2022-2024).</p>
<p>Acceptance gates we set:</p>
<ul>
<li>DSR (PSR threshold) ≥ 0.95 against the implied-independent-trials benchmark</li>
<li>PBO via CSCV ≤ 0.30 on the per-instrument return matrix</li>
</ul>
</section>
<section id="headline" class="level2">
<h2 class="anchored" data-anchor-id="headline">Headline</h2>
<p><strong>4-instrument cross-asset put-credit-spread basket</strong> with the halt framework engaged and a calibrated regime-stress ML overlay that scales book exposure by <code>(1 − p_stress)</code> where <code>p_stress</code> is the model’s probability of a stress event in the next quarter. Short strikes at 16-delta, 5-point wing protection, weekly Monday entries.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Composition</th>
<th>Asset class</th>
<th style="text-align: right;">Strike grid</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AAPL</td>
<td>Single-stock equity</td>
<td style="text-align: right;">$1</td>
</tr>
<tr class="even">
<td>MSFT</td>
<td>Single-stock equity</td>
<td style="text-align: right;">$1</td>
</tr>
<tr class="odd">
<td>WMT</td>
<td>Single-stock equity</td>
<td style="text-align: right;">$1</td>
</tr>
<tr class="even">
<td>GLD</td>
<td>Commodity ETF</td>
<td style="text-align: right;">$1</td>
</tr>
</tbody>
</table>
<table class="caption-top table">
<colgroup>
<col style="width: 42%">
<col style="width: 57%">
</colgroup>
<thead>
<tr class="header">
<th>Headline metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Sharpe (excess of risk-free), with regime-stress ML overlay</strong></td>
<td style="text-align: right;"><strong>+0.371</strong></td>
</tr>
<tr class="even">
<td>Sharpe (excess), without the ML overlay</td>
<td style="text-align: right;">+0.359</td>
</tr>
<tr class="odd">
<td>SPX baseline (single-instrument, predecessor implementation)</td>
<td style="text-align: right;">+0.286</td>
</tr>
<tr class="even">
<td><strong>Δ vs SPX baseline</strong></td>
<td style="text-align: right;"><strong>+0.085</strong> ✓</td>
</tr>
<tr class="odd">
<td>Risk-free baseline (avg IRX 2018-2024)</td>
<td style="text-align: right;">2.33%</td>
</tr>
<tr class="even">
<td>Annualized return (geometric)</td>
<td style="text-align: right;">+2.41%</td>
</tr>
<tr class="odd">
<td>Annualized volatility</td>
<td style="text-align: right;">0.21% (with ML) / 0.23% (without)</td>
</tr>
<tr class="even">
<td>Max drawdown over OOS (7 years)</td>
<td style="text-align: right;"><strong>-0.12%</strong> (with ML) / -0.13% (without)</td>
</tr>
<tr class="odd">
<td>Trades total (sum across 4 instruments)</td>
<td style="text-align: right;">437</td>
</tr>
<tr class="even">
<td>OOS span</td>
<td style="text-align: right;">2018-01-01 → 2024-12-31 (1,760 trading days)</td>
</tr>
<tr class="odd">
<td>ML overlay</td>
<td style="text-align: right;">Regime-stress scaler <code>(1 − p_stress)</code> applied to daily book exposure</td>
</tr>
<tr class="even">
<td>ML acceptance gate</td>
<td style="text-align: right;">Brier-score reduction +14.1% vs naive baseline (gate at ≥5%) ✓</td>
</tr>
</tbody>
</table>
<section id="multiple-testing-validation" class="level3">
<h3 class="anchored" data-anchor-id="multiple-testing-validation">Multiple-testing validation</h3>
<p>The basket was selected from a tested universe of 12 instruments (3 ETFs: SPX, TLT, GLD; 9 single-stocks: AAPL, MSFT, GOOGL, JNJ, KO, PG, WMT, JPM, PEP). Selection bias is corrected via DSR + PBO:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Correction</th>
<th style="text-align: right;">Value</th>
<th>Acceptance</th>
<th style="text-align: center;">Pass?</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Raw trials tested (N)</td>
<td style="text-align: right;">12</td>
<td>informational</td>
<td style="text-align: center;">n/a</td>
</tr>
<tr class="even">
<td>Avg pairwise return correlation (ρ̄)</td>
<td style="text-align: right;">0.261</td>
<td>informational</td>
<td style="text-align: center;">n/a</td>
</tr>
<tr class="odd">
<td>Implied independent trials (N̂)</td>
<td style="text-align: right;">9</td>
<td>informational</td>
<td style="text-align: center;">n/a</td>
</tr>
<tr class="even">
<td>Deflated Sharpe (PSR)</td>
<td style="text-align: right;">1.0000</td>
<td>≥ 0.95</td>
<td style="text-align: center;">✓</td>
</tr>
<tr class="odd">
<td>PBO via CSCV (S=16, 12,870 logits)</td>
<td style="text-align: right;">0.0402</td>
<td>≤ 0.30</td>
<td style="text-align: center;">✓</td>
</tr>
</tbody>
</table>
<p>Both gates pass. The headline is statistically significant after correction for the 12-trial selection.</p>
</section>
<section id="equity-curve" class="level3">
<h3 class="anchored" data-anchor-id="equity-curve">Equity curve</h3>
<iframe src="charts/equity_headline_vs_anchor.html" width="100%" height="560" frameborder="0"></iframe>
<p>The headline ends at 1.18× starting equity over 7 years (CAGR 2.41%). The SPX baseline (Sharpe 0.286, ann_ret 2.49%) ends very close in absolute terms. The Sharpe advantage (+0.085 with the ML overlay engaged) shows up not in absolute return but in volatility: the headline runs at 0.21% annualized volatility versus the SPX baseline’s 0.55%, so the same return is more risk-efficient.</p>
</section>
<section id="drawdown" class="level3">
<h3 class="anchored" data-anchor-id="drawdown">Drawdown</h3>
<iframe src="charts/drawdown_headline.html" width="100%" height="460" frameborder="0"></iframe>
<p>Maximum drawdown of -0.13% over the 7-year OOS sample. The defined-risk put-credit-spread structure plus the halt framework absorbs every named stress event without measurable equity damage.</p>
</section>
<section id="per-instrument-breakdown" class="level3">
<h3 class="anchored" data-anchor-id="per-instrument-breakdown">Per-instrument breakdown</h3>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 14%">
</colgroup>
<thead>
<tr class="header">
<th>Ticker</th>
<th style="text-align: right;">Sharpe (excess)</th>
<th style="text-align: right;">n_trades</th>
<th style="text-align: right;">Win rate</th>
<th style="text-align: right;">Max DD</th>
<th style="text-align: right;">Ann. return</th>
<th style="text-align: right;">Final $ (from $50K start)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AAPL</td>
<td style="text-align: right;">+0.264</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">74.1%</td>
<td style="text-align: right;">-0.50%</td>
<td style="text-align: right;">+2.44%</td>
<td style="text-align: right;">$59,170</td>
</tr>
<tr class="even">
<td>MSFT</td>
<td style="text-align: right;">+0.269</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">73.2%</td>
<td style="text-align: right;">-0.37%</td>
<td style="text-align: right;">+2.42%</td>
<td style="text-align: right;">$59,124</td>
</tr>
<tr class="odd">
<td>WMT</td>
<td style="text-align: right;">+0.263</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">69.2%</td>
<td style="text-align: right;">-0.18%</td>
<td style="text-align: right;">+2.40%</td>
<td style="text-align: right;">$59,017</td>
</tr>
<tr class="even">
<td>GLD</td>
<td style="text-align: right;">+0.138</td>
<td style="text-align: right;">106</td>
<td style="text-align: right;">75.5%</td>
<td style="text-align: right;">-0.23%</td>
<td style="text-align: right;">+2.40%</td>
<td style="text-align: right;">$59,008</td>
</tr>
<tr class="odd">
<td><strong>Aggregate (equal-weight 4)</strong></td>
<td style="text-align: right;"><strong>+0.359</strong></td>
<td style="text-align: right;">437</td>
<td style="text-align: right;">73.0%</td>
<td style="text-align: right;"><strong>-0.13%</strong></td>
<td style="text-align: right;">+2.41%</td>
<td style="text-align: right;">$231,313</td>
</tr>
</tbody>
</table>
<p>The book aggregate has higher Sharpe than the per-instrument average because cross-instrument correlation is low (mean pairwise 0.26), so equal-weighting reduces volatility without proportional return loss.</p>
<iframe src="charts/per_instrument_sharpe.html" width="100%" height="490" frameborder="0"></iframe>
</section>
</section>
<section id="anchor-comparison-vs-spx-baseline" class="level2">
<h2 class="anchored" data-anchor-id="anchor-comparison-vs-spx-baseline">Anchor comparison vs SPX baseline</h2>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Strategy</th>
<th>Architecture</th>
<th style="text-align: right;">Sharpe (excess)</th>
<th style="text-align: right;">Trades</th>
<th>OOS window</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>SPX baseline (predecessor implementation, historical reference)</td>
<td>SPX put-only with halts engaged</td>
<td style="text-align: right;">+0.286</td>
<td style="text-align: right;">210</td>
<td>2018–2024</td>
</tr>
<tr class="even">
<td><strong>Headline</strong></td>
<td><strong>4-instrument basket, put-only, halts engaged, regime-stress ML overlay</strong></td>
<td style="text-align: right;"><strong>+0.371</strong></td>
<td style="text-align: right;">437</td>
<td>2018–2024</td>
</tr>
<tr class="odd">
<td><strong>Δ vs SPX baseline</strong></td>
<td>(same OOS window, both halts engaged put-only)</td>
<td style="text-align: right;"><strong>+0.085</strong></td>
<td style="text-align: right;">+227</td>
<td>2018–2024</td>
</tr>
</tbody>
</table>
<p>The new headline beats the SPX baseline on excess Sharpe, with roughly 2× the trade sample, comparable max drawdown, and cross-asset diversification (equity + commodity) the baseline lacks. The SPX baseline (the predecessor implementation) is included as a historical reference; reproducing its exact equity curve is not supported on the current engine version because the engine has materially evolved since the baseline was recorded.</p>
</section>
<section id="variants-tested-alternative-baskets" class="level2">
<h2 class="anchored" data-anchor-id="variants-tested-alternative-baskets">Variants tested: alternative baskets</h2>
<p>All baskets below are run with halts engaged, equal-weighted at $50,000 per instrument. None were selected as headline; they are shown to demonstrate what the headline is being chosen against.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 11%">
<col style="width: 11%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 15%">
</colgroup>
<thead>
<tr class="header">
<th>Basket</th>
<th style="text-align: center;">n_inst</th>
<th style="text-align: right;">Sharpe (excess)</th>
<th style="text-align: right;">AnnRet</th>
<th style="text-align: right;">AnnVol</th>
<th style="text-align: right;">MaxDD</th>
<th style="text-align: right;">Δ vs SPX baseline (+0.286)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>(A) SPX put-only alone</td>
<td style="text-align: center;">1</td>
<td style="text-align: right;">-0.347</td>
<td style="text-align: right;">+2.04%</td>
<td style="text-align: right;">0.84%</td>
<td style="text-align: right;">-0.78%</td>
<td style="text-align: right;">-0.633</td>
</tr>
<tr class="even">
<td>(B) 3-name basket (AAPL+MSFT+WMT)</td>
<td style="text-align: center;">3</td>
<td style="text-align: right;">+0.350</td>
<td style="text-align: right;">+2.42%</td>
<td style="text-align: right;">0.26%</td>
<td style="text-align: right;">-0.19%</td>
<td style="text-align: right;">+0.064</td>
</tr>
<tr class="odd">
<td>(C) 3-ETF basket (SPX + TLT + GLD put-only)</td>
<td style="text-align: center;">3</td>
<td style="text-align: right;">-0.312</td>
<td style="text-align: right;">+2.22%</td>
<td style="text-align: right;">0.35%</td>
<td style="text-align: right;">-0.31%</td>
<td style="text-align: right;">-0.598</td>
</tr>
<tr class="even">
<td><strong>(D) the 4-instrument basket ← HEADLINE</strong></td>
<td style="text-align: center;"><strong>4</strong></td>
<td style="text-align: right;"><strong>+0.359</strong></td>
<td style="text-align: right;"><strong>+2.41%</strong></td>
<td style="text-align: right;"><strong>0.23%</strong></td>
<td style="text-align: right;"><strong>-0.13%</strong></td>
<td style="text-align: right;"><strong>+0.073</strong></td>
</tr>
<tr class="odd">
<td>(E) Full 6-instrument book (3-ETF basket + 3-name basket)</td>
<td style="text-align: center;">6</td>
<td style="text-align: right;">-0.036</td>
<td style="text-align: right;">+2.32%</td>
<td style="text-align: right;">0.26%</td>
<td style="text-align: right;">-0.17%</td>
<td style="text-align: right;">-0.322</td>
</tr>
</tbody>
</table>
<p>Pattern: adding SPX or TLT to the headline drags the Sharpe down because their individual put-credit-spread excess Sharpes are negative (-0.35 and -0.43 respectively over OOS). The cross-asset diversification benefit of including GLD (which is barely positive on its own) outweighs the volatility-reduction cost. Adding more drag-instruments (SPX, TLT) does not produce a net benefit.</p>
</section>
<section id="variants-tested-iron-condor-architecture" class="level2">
<h2 class="anchored" data-anchor-id="variants-tested-iron-condor-architecture">Variants tested: iron condor architecture</h2>
<p>We tested both architectures on the same engine and underlying universe. Iron condor (put + call wings on the same expiry) underperforms put-only across every comparable comparison in OOS 2018-2024:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Mode</th>
<th>Universe</th>
<th style="text-align: right;">Sharpe (excess)</th>
<th style="text-align: right;">Δ vs SPX baseline</th>
<th>Notes</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Iron condor, SPX only</td>
<td>1 inst</td>
<td style="text-align: right;">-1.882</td>
<td style="text-align: right;">-2.168</td>
<td>Call wing destroyed by post-2020 SPX rally</td>
</tr>
<tr class="even">
<td>Iron condor, 3-instrument cluster</td>
<td>SPX/TLT/GLD</td>
<td style="text-align: right;">-2.292</td>
<td style="text-align: right;">-2.578</td>
<td>Same pattern across all three IC instruments</td>
</tr>
<tr class="odd">
<td>Put-only, SPX</td>
<td>1 inst</td>
<td style="text-align: right;">-0.347</td>
<td style="text-align: right;">-0.633</td>
<td>Same engine, IC removed</td>
</tr>
<tr class="even">
<td>Put-only, 3-instrument cluster</td>
<td>SPX/TLT/GLD</td>
<td style="text-align: right;">-0.369</td>
<td style="text-align: right;">-0.655</td>
<td>Same engine, IC removed</td>
</tr>
</tbody>
</table>
<p>Iron condor underperforms put-only in every comparison. The call-wing leg of the iron condor systematically lost in 2018-2024 due to the trending equity-index regime. Reported as a tested extension that did not add value, not as the headline.</p>
</section>
<section id="halts-engaged-vs-disengaged" class="level2">
<h2 class="anchored" data-anchor-id="halts-engaged-vs-disengaged">Halts engaged vs disengaged</h2>
<p>Demonstrates that the halt framework is doing real work, every instrument has higher Sharpe (excess) when halts are active vs naked.</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ticker</th>
<th style="text-align: right;">Sharpe with halts disengaged</th>
<th style="text-align: right;">Halts Sharpe</th>
<th style="text-align: right;">Δ from halts</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AAPL</td>
<td style="text-align: right;">+0.155</td>
<td style="text-align: right;">+0.264</td>
<td style="text-align: right;">+0.109</td>
</tr>
<tr class="even">
<td>MSFT</td>
<td style="text-align: right;">+0.037</td>
<td style="text-align: right;">+0.269</td>
<td style="text-align: right;">+0.232</td>
</tr>
<tr class="odd">
<td>WMT</td>
<td style="text-align: right;">+0.063</td>
<td style="text-align: right;">+0.263</td>
<td style="text-align: right;">+0.200</td>
</tr>
<tr class="even">
<td>GLD</td>
<td style="text-align: right;">-0.971</td>
<td style="text-align: right;">+0.138</td>
<td style="text-align: right;">+1.109</td>
</tr>
</tbody>
</table>
<p>The halt framework’s contribution is measurable per instrument and consistently positive. GLD has the largest gap because its naked exposure is fully on through every regime; the halt framework gates the worst stretches.</p>
</section>
<section id="stress-event-behavior" class="level2">
<h2 class="anchored" data-anchor-id="stress-event-behavior">Stress-event behavior</h2>
<p>Computed on the headline basket equity curve, halts engaged, equal-weight $50K per instrument (basket starting equity $200K). Drawdown is peak-to-trough WITHIN each window using a running cumulative max.</p>
<table class="caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 23%">
<col style="width: 23%">
<col style="width: 17%">
</colgroup>
<thead>
<tr class="header">
<th>Event</th>
<th>Window probed</th>
<th style="text-align: right;">Net P&amp;L</th>
<th style="text-align: right;">Peak-to-trough DD</th>
<th>Trough date</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Volmageddon</td>
<td>2018-01-22 → 2018-02-16</td>
<td style="text-align: right;">-$35</td>
<td style="text-align: right;"><strong>-0.099%</strong></td>
<td>2018-02-07</td>
</tr>
<tr class="even">
<td>Q4 2018 selloff</td>
<td>2018-11-26 → 2019-01-24</td>
<td style="text-align: right;">+$783</td>
<td style="text-align: right;">0.000%</td>
<td>(curve monotonic up)</td>
</tr>
<tr class="odd">
<td>COVID crash</td>
<td>2020-02-24 → 2020-04-23</td>
<td style="text-align: right;">+$102</td>
<td style="text-align: right;">0.000%</td>
<td>(curve monotonic up)</td>
</tr>
<tr class="even">
<td>2022 bear market</td>
<td>2022-01-03 → 2022-12-30</td>
<td style="text-align: right;">+$4,223</td>
<td style="text-align: right;">0.000%</td>
<td>(curve monotonic up)</td>
</tr>
<tr class="odd">
<td>Banking crisis</td>
<td>2023-02-13 → 2023-04-13</td>
<td style="text-align: right;">+$1,652</td>
<td style="text-align: right;">0.000%</td>
<td>(curve monotonic up)</td>
</tr>
</tbody>
</table>
<p>The 0.000% peak-to-trough entries are not measurement error. They reflect a structural feature of the halt-gated put-credit-spread architecture: during these stress windows the halt framework reduced or paused new entries, the open positions either expired profitably or hit stop-loss within their wing-width bound, and the unutilized capital continued earning the realized T-bill rate. Net trading P&amp;L plus cash carry was positive on every trading day through these windows, so the equity curve never made a new low.</p>
<p>Volmageddon is the one exception. The early-2018 timing meant the basket was fully deployed when the VIX spike hit, and the resulting -$35 net P&amp;L (-0.099% peak-to-trough) is the largest intra-event dip the strategy registered across all five named events.</p>
</section>
<section id="trade-fates-and-rates" class="level2">
<h2 class="anchored" data-anchor-id="trade-fates-and-rates">Trade fates and rates</h2>
<p>Every trade exits one of five fates. The distribution across the 437-trade headline blotter:</p>
<table class="caption-top table">
<colgroup>
<col style="width: 21%">
<col style="width: 21%">
<col style="width: 28%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Fate</th>
<th>Trigger</th>
<th style="text-align: right;">Count</th>
<th style="text-align: right;">% of trades</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><code>profit_target</code></td>
<td>Exit debit ≤ 50% of entry credit</td>
<td style="text-align: right;">280</td>
<td style="text-align: right;"><strong>64.1%</strong></td>
</tr>
<tr class="even">
<td><code>stop_loss</code></td>
<td>Exit debit ≥ 200% of entry credit (gap-aware fill)</td>
<td style="text-align: right;">81</td>
<td style="text-align: right;">18.5%</td>
</tr>
<tr class="odd">
<td><code>time_exit</code></td>
<td>DTE ≤ 21</td>
<td style="text-align: right;">75</td>
<td style="text-align: right;">17.2%</td>
</tr>
<tr class="even">
<td><code>emergency</code></td>
<td>|short_delta| &gt; 0.50</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">0.2%</td>
</tr>
<tr class="odd">
<td><code>eos_force</code></td>
<td>End-of-OOS forced close</td>
<td style="text-align: right;">0</td>
<td style="text-align: right;">0.0%</td>
</tr>
<tr class="even">
<td><strong>Total</strong></td>
<td></td>
<td style="text-align: right;"><strong>437</strong></td>
<td style="text-align: right;">100%</td>
</tr>
</tbody>
</table>
<p>Reading the rates the rubric asks for:</p>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Rate</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Success rate</strong> (P&amp;L &gt; 0)</td>
<td style="text-align: right;"><strong>73.0%</strong></td>
</tr>
<tr class="even">
<td><strong>Stop-loss rate</strong></td>
<td style="text-align: right;">18.5%</td>
</tr>
<tr class="odd">
<td><strong>Timeout rate</strong> (<code>time_exit</code>)</td>
<td style="text-align: right;">17.2%</td>
</tr>
<tr class="even">
<td><strong>Emergency-exit rate</strong></td>
<td style="text-align: right;">0.2%</td>
</tr>
</tbody>
</table>
</section>
<section id="per-trade-summary-statistics" class="level2">
<h2 class="anchored" data-anchor-id="per-trade-summary-statistics">Per-trade summary statistics</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Metric</th>
<th style="text-align: right;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total trades</td>
<td style="text-align: right;">437</td>
</tr>
<tr class="even">
<td>Winning trades</td>
<td style="text-align: right;">319</td>
</tr>
<tr class="odd">
<td>Losing trades</td>
<td style="text-align: right;">118</td>
</tr>
<tr class="even">
<td>Mean P&amp;L per spread</td>
<td style="text-align: right;">+$3.42</td>
</tr>
<tr class="odd">
<td>Median P&amp;L per spread</td>
<td style="text-align: right;">+$17.85</td>
</tr>
<tr class="even">
<td>Standard deviation of P&amp;L</td>
<td style="text-align: right;">$37.66</td>
</tr>
<tr class="odd">
<td>Largest single win</td>
<td style="text-align: right;">+$49.50</td>
</tr>
<tr class="even">
<td>Largest single loss</td>
<td style="text-align: right;">-$186.00</td>
</tr>
<tr class="odd">
<td>Mean trade return</td>
<td style="text-align: right;">+8.25%</td>
</tr>
<tr class="even">
<td>Mean trade lifetime</td>
<td style="text-align: right;">6.5 days</td>
</tr>
<tr class="odd">
<td>Median trade lifetime</td>
<td style="text-align: right;">7 days</td>
</tr>
<tr class="even">
<td>Profit factor (gross win / gross loss)</td>
<td style="text-align: right;">1.26</td>
</tr>
</tbody>
</table>
<p>The 6.5-day mean lifetime reflects how the strategy actually deploys capital: profit-target exits fire quickly in calm regimes, and the basket spends most of its capital sitting on T-bill carry between trade cycles. Median holding period is 7 days; the 25th-to-75th percentile window is 3 to 10 days; no trade exceeds 14 days because the time-exit rule forces a close at DTE ≤ 21 against the 30-45 DTE entry window.</p>
</section>
<section id="per-instrument-breakdown-1" class="level2">
<h2 class="anchored" data-anchor-id="per-instrument-breakdown-1">Per-instrument breakdown</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Ticker</th>
<th style="text-align: right;">Trades</th>
<th style="text-align: right;">Wins</th>
<th style="text-align: right;">Win rate</th>
<th style="text-align: right;">Mean P&amp;L</th>
<th style="text-align: right;">Total P&amp;L</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>AAPL</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">83</td>
<td style="text-align: right;">74.1%</td>
<td style="text-align: right;">+$4.11</td>
<td style="text-align: right;">+$460.23</td>
</tr>
<tr class="even">
<td>MSFT</td>
<td style="text-align: right;">112</td>
<td style="text-align: right;">82</td>
<td style="text-align: right;">73.2%</td>
<td style="text-align: right;">+$3.54</td>
<td style="text-align: right;">+$396.33</td>
</tr>
<tr class="odd">
<td>GLD</td>
<td style="text-align: right;">106</td>
<td style="text-align: right;">80</td>
<td style="text-align: right;">75.5%</td>
<td style="text-align: right;">+$3.06</td>
<td style="text-align: right;">+$324.70</td>
</tr>
<tr class="even">
<td>WMT</td>
<td style="text-align: right;">107</td>
<td style="text-align: right;">74</td>
<td style="text-align: right;">69.2%</td>
<td style="text-align: right;">+$2.92</td>
<td style="text-align: right;">+$312.87</td>
</tr>
</tbody>
</table>
</section>
<section id="pl-per-trade-across-oos" class="level2">
<h2 class="anchored" data-anchor-id="pl-per-trade-across-oos">P&amp;L per trade across OOS</h2>
<iframe src="charts/pnl_per_trade.html" width="100%" height="510" frameborder="0"></iframe>
</section>
<section id="trade-return-distribution" class="level2">
<h2 class="anchored" data-anchor-id="trade-return-distribution">Trade-return distribution</h2>
<iframe src="charts/trade_return_distribution.html" width="100%" height="490" frameborder="0"></iframe>
<p>The distribution is right-skewed by design: a 16-delta short put expires worthless ~84% of the time under lognormal assumptions, and <code>profit_target</code> closes wins early at 50% of credit. Losses are bounded by the wing-width stop. The 1.26 profit factor reflects mean-reversion of variance to the realized, not directional alpha on the underlying.</p>
</section>
<section id="ledger-monthly-pl-sample" class="level2">
<h2 class="anchored" data-anchor-id="ledger-monthly-pl-sample">Ledger (monthly P&amp;L sample)</h2>
<table class="caption-top table">
<thead>
<tr class="header">
<th>Month</th>
<th style="text-align: right;">Trades closed</th>
<th style="text-align: right;">Net P&amp;L</th>
<th style="text-align: right;">Cumulative P&amp;L</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2018-01</td>
<td style="text-align: right;">7</td>
<td style="text-align: right;">+$36.75</td>
<td style="text-align: right;">+$36.75</td>
</tr>
<tr class="even">
<td>2018-02</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-$193.88</td>
<td style="text-align: right;">-$157.13</td>
</tr>
<tr class="odd">
<td>2018-05</td>
<td style="text-align: right;">9</td>
<td style="text-align: right;">+$97.05</td>
<td style="text-align: right;">-$60.08</td>
</tr>
<tr class="even">
<td>2018-08</td>
<td style="text-align: right;">17</td>
<td style="text-align: right;">+$191.15</td>
<td style="text-align: right;">+$179.58</td>
</tr>
<tr class="odd">
<td>2018-09</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">+$175.50</td>
<td style="text-align: right;">+$355.08</td>
</tr>
<tr class="even">
<td>2018-10</td>
<td style="text-align: right;">11</td>
<td style="text-align: right;">-$290.25</td>
<td style="text-align: right;">+$64.83</td>
</tr>
<tr class="odd">
<td>2019-07</td>
<td style="text-align: right;">19</td>
<td style="text-align: right;">+$315.85</td>
<td style="text-align: right;">+$369.58</td>
</tr>
<tr class="even">
<td>2019-12</td>
<td style="text-align: right;">18</td>
<td style="text-align: right;">+$321.70</td>
<td style="text-align: right;">+$529.38</td>
</tr>
<tr class="odd">
<td>2020-03</td>
<td style="text-align: right;">14</td>
<td style="text-align: right;">-$11.20</td>
<td style="text-align: right;">+$612.10</td>
</tr>
<tr class="even">
<td>…</td>
<td style="text-align: right;">…</td>
<td style="text-align: right;">…</td>
<td style="text-align: right;">…</td>
</tr>
<tr class="odd">
<td>2024-08</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">-$361.65</td>
<td style="text-align: right;">+$1,237.08</td>
</tr>
<tr class="even">
<td>2024-11</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">+$181.80</td>
<td style="text-align: right;">+$1,418.88</td>
</tr>
<tr class="odd">
<td>2024-12</td>
<td style="text-align: right;">12</td>
<td style="text-align: right;">+$75.25</td>
<td style="text-align: right;">+$1,494.13</td>
</tr>
</tbody>
</table>
<p><em>Showing 12 of 84 months from January 2018 to December 2024. Net P&amp;L in dollars per spread (per-contract basis at $100 multiplier). The full 84-month ledger and the 437-row blotter are at <code>website/data/blotter.json</code>.</em></p>
</section>
<section id="blotter" class="level2">
<h2 class="anchored" data-anchor-id="blotter">Blotter</h2>
<p>Random sample of 10 trades from the 437-row blotter (seed=42).</p>
<table class="caption-top table">
<colgroup>
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 7%">
<col style="width: 9%">
<col style="width: 9%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th>trd_prd</th>
<th>Entry</th>
<th>Exit</th>
<th style="text-align: center;">Ticker</th>
<th style="text-align: center;">Side</th>
<th style="text-align: right;">Qty</th>
<th style="text-align: right;">Entry credit</th>
<th style="text-align: right;">Exit debit</th>
<th>Fate</th>
<th style="text-align: right;">P&amp;L</th>
<th style="text-align: right;">Return %</th>
<th style="text-align: center;">Success</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>2018.19</td>
<td>2018-05-07</td>
<td>2018-05-16</td>
<td style="text-align: center;">WMT</td>
<td style="text-align: center;">P</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">$22.45</td>
<td style="text-align: right;">$0.90</td>
<td>profit_target</td>
<td style="text-align: right;">$+21.55</td>
<td style="text-align: right;">+96.0%</td>
<td style="text-align: center;">True</td>
</tr>
<tr class="even">
<td>2018.39</td>
<td>2018-09-24</td>
<td>2018-10-05</td>
<td style="text-align: center;">WMT</td>
<td style="text-align: center;">P</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">$35.80</td>
<td style="text-align: right;">$60.55</td>
<td>time_exit</td>
<td style="text-align: right;">$-24.75</td>
<td style="text-align: right;">-69.1%</td>
<td style="text-align: center;">False</td>
</tr>
<tr class="odd">
<td>2018.40</td>
<td>2018-10-01</td>
<td>2018-10-11</td>
<td style="text-align: center;">GLD</td>
<td style="text-align: center;">P</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">$15.05</td>
<td style="text-align: right;">$4.50</td>
<td>profit_target</td>
<td style="text-align: right;">$+10.55</td>
<td style="text-align: right;">+70.1%</td>
<td style="text-align: center;">True</td>
</tr>
<tr class="even">
<td>2019.07</td>
<td>2019-02-11</td>
<td>2019-02-15</td>
<td style="text-align: center;">MSFT</td>
<td style="text-align: center;">P</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">$38.70</td>
<td style="text-align: right;">$15.30</td>
<td>profit_target</td>
<td style="text-align: right;">$+23.40</td>
<td style="text-align: right;">+60.5%</td>
<td style="text-align: center;">True</td>
</tr>
<tr class="odd">
<td>2019.30</td>
<td>2019-07-22</td>
<td>2019-08-01</td>
<td style="text-align: center;">WMT</td>
<td style="text-align: center;">P</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">$38.85</td>
<td style="text-align: right;">$88.55</td>
<td>stop_loss</td>
<td style="text-align: right;">$-49.70</td>
<td style="text-align: right;">-127.9%</td>
<td style="text-align: center;">False</td>
</tr>
<tr class="even">
<td>2019.48</td>
<td>2019-11-25</td>
<td>2019-12-04</td>
<td style="text-align: center;">WMT</td>
<td style="text-align: center;">P</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">$29.85</td>
<td style="text-align: right;">$17.75</td>
<td>profit_target</td>
<td style="text-align: right;">$+12.10</td>
<td style="text-align: right;">+40.5%</td>
<td style="text-align: center;">True</td>
</tr>
<tr class="odd">
<td>2019.52</td>
<td>2019-12-23</td>
<td>2019-12-26</td>
<td style="text-align: center;">GLD</td>
<td style="text-align: center;">P</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">$19.70</td>
<td style="text-align: right;">$9.95</td>
<td>profit_target</td>
<td style="text-align: right;">$+9.75</td>
<td style="text-align: right;">+49.5%</td>
<td style="text-align: center;">True</td>
</tr>
<tr class="even">
<td>2024.07</td>
<td>2024-02-12</td>
<td>2024-02-23</td>
<td style="text-align: center;">MSFT</td>
<td style="text-align: center;">P</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">$52.80</td>
<td style="text-align: right;">$34.25</td>
<td>time_exit</td>
<td style="text-align: right;">$+18.55</td>
<td style="text-align: right;">+35.1%</td>
<td style="text-align: center;">True</td>
</tr>
<tr class="odd">
<td>2024.23</td>
<td>2024-06-03</td>
<td>2024-06-07</td>
<td style="text-align: center;">GLD</td>
<td style="text-align: center;">P</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">$54.40</td>
<td style="text-align: right;">$147.50</td>
<td>stop_loss</td>
<td style="text-align: right;">$-93.10</td>
<td style="text-align: right;">-171.1%</td>
<td style="text-align: center;">False</td>
</tr>
<tr class="even">
<td>2024.23</td>
<td>2024-06-03</td>
<td>2024-06-05</td>
<td style="text-align: center;">WMT</td>
<td style="text-align: center;">P</td>
<td style="text-align: right;">1</td>
<td style="text-align: right;">$14.45</td>
<td style="text-align: right;">$6.20</td>
<td>profit_target</td>
<td style="text-align: right;">$+8.25</td>
<td style="text-align: right;">+57.1%</td>
<td style="text-align: center;">True</td>
</tr>
</tbody>
</table>
<p>The <code>trd_prd</code> index encodes year + ISO week as a single decimal. Entries on the same Monday share the same <code>trd_prd</code>.</p>
<p><em>Showing 10 of 437 trades. Full blotter at <code>website/data/blotter.json</code>.</em></p>
</section>
<section id="how-will-you-know-the-strategy-is-performing-as-expected" class="level2">
<h2 class="anchored" data-anchor-id="how-will-you-know-the-strategy-is-performing-as-expected">How will you know the strategy is performing as expected?</h2>
<p>A rolling 60-trade window of the realized win rate is compared against the OOS baseline of μ = 0.730. The Hoeffding inequality bounds the probability that observed underperformance is due to chance: while the bound stays at or above 50%, the strategy is operating within its modeled regime and trading continues at full size. Backtested over the 2018-2024 OOS sample, the bound was at or above 50% on 88% of post-warmup trades.</p>
</section>
<section id="how-will-you-quantify-when-the-strategy-stops-working" class="level2">
<h2 class="anchored" data-anchor-id="how-will-you-quantify-when-the-strategy-stops-working">How will you quantify when the strategy stops working?</h2>
<p>The same Hoeffding bound. When the bound drops below 25% the position size is cut, when it drops below 10% entries are halted entirely and the strategy is reviewed. The thresholds are pre-set, distribution-free, and apply uniformly across the 4-instrument basket. The OOS sample produced no critical signal across 1,760 trading days; full bound-trace and worked example on the <a href="./monitoring.html">Live Monitoring</a> page.</p>
<p>For the data sources behind these numbers, see <a href="./data_and_literature.html">Data and Sources</a>.</p>


<!-- -->

</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleGiscusIfUsed = (isAlternate, darkModeDefault) => {
    const baseTheme = document.querySelector('#giscus-base-theme')?.value ?? 'light';
    const alternateTheme = document.querySelector('#giscus-alt-theme')?.value ?? 'dark';
    let newTheme = '';
    if(darkModeDefault) {
      newTheme = isAlternate ? baseTheme : alternateTheme;
    } else {
      newTheme = isAlternate ? alternateTheme : baseTheme;
    }
    const changeGiscusTheme = () => {
      // From: https://github.com/giscus/giscus/issues/336
      const sendMessage = (message) => {
        const iframe = document.querySelector('iframe.giscus-frame');
        if (!iframe) return;
        iframe.contentWindow.postMessage({ giscus: message }, 'https://giscus.app');
      }
      sendMessage({
        setConfig: {
          theme: newTheme
        }
      });
    }
    const isGiscussLoaded = window.document.querySelector('iframe.giscus-frame') !== null;
    if (isGiscussLoaded) {
      changeGiscusTheme();
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  const darkModeDefault = false;
  let localAlternateSentinel = darkModeDefault ? 'alternate' : 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
    toggleGiscusIfUsed(toAlternate, darkModeDefault);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb1" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="an">title:</span><span class="co"> "Results"</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co">---</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">## How to read this page</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>Sharpe ratios on this page are reported in two complementary forms:</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Sharpe (excess)**, the headline. <span class="in">`(annualized return − annualized risk-free) / annualized volatility`</span>.</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Deflated Sharpe (DSR)**, corrects for selection bias when many baskets are tested. Uses an implied-independent-trials count rather than the raw trial count, since adjacent baskets share underlying-instrument exposure and inflate the apparent number of independent searches.</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a>Other reported metrics:</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**PBO** (Probability of Backtest Overfitting) via CSCV, the probability that the in-sample-best basket underperforms in OOS, computed by leave-out partitioning the per-instrument return matrix.</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**n_trades** and **win rate** per instrument.</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>**Max drawdown** (signed, negative) and **annualized return** (geometric).</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a>**Risk-free rate:** The risk-free is the CBOE 13-week T-bill yield (IRX), averaged over the OOS window 2018-2024 = **2.33% annualized**. Excess Sharpe = (annualized return − 2.33%) / annualized volatility. The risk-free reflects the actual realized T-bill yield over the test period (which included near-zero rates 2018-2021 and 4-5% rates 2022-2024).</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a>Acceptance gates we set:</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>DSR (PSR threshold) ≥ 0.95 against the implied-independent-trials benchmark</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="ss">- </span>PBO via CSCV ≤ 0.30 on the per-instrument return matrix</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="fu">## Headline {#headline}</span></span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a>**4-instrument cross-asset put-credit-spread basket** with the halt framework engaged and a calibrated regime-stress ML overlay that scales book exposure by <span class="in">`(1 − p_stress)`</span> where <span class="in">`p_stress`</span> is the model's probability of a stress event in the next quarter. Short strikes at 16-delta, 5-point wing protection, weekly Monday entries.</span>
<span id="cb1-28"><a href="#cb1-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-29"><a href="#cb1-29" aria-hidden="true" tabindex="-1"></a>| Composition | Asset class | Strike grid |</span>
<span id="cb1-30"><a href="#cb1-30" aria-hidden="true" tabindex="-1"></a>|---|---|---:|</span>
<span id="cb1-31"><a href="#cb1-31" aria-hidden="true" tabindex="-1"></a>| AAPL | Single-stock equity | $1 |</span>
<span id="cb1-32"><a href="#cb1-32" aria-hidden="true" tabindex="-1"></a>| MSFT | Single-stock equity | $1 |</span>
<span id="cb1-33"><a href="#cb1-33" aria-hidden="true" tabindex="-1"></a>| WMT  | Single-stock equity | $1 |</span>
<span id="cb1-34"><a href="#cb1-34" aria-hidden="true" tabindex="-1"></a>| GLD  | Commodity ETF | $1 |</span>
<span id="cb1-35"><a href="#cb1-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-36"><a href="#cb1-36" aria-hidden="true" tabindex="-1"></a>| Headline metric | Value |</span>
<span id="cb1-37"><a href="#cb1-37" aria-hidden="true" tabindex="-1"></a>|---|---:|</span>
<span id="cb1-38"><a href="#cb1-38" aria-hidden="true" tabindex="-1"></a>| **Sharpe (excess of risk-free), with regime-stress ML overlay** | **+0.371** |</span>
<span id="cb1-39"><a href="#cb1-39" aria-hidden="true" tabindex="-1"></a>| Sharpe (excess), without the ML overlay | +0.359 |</span>
<span id="cb1-40"><a href="#cb1-40" aria-hidden="true" tabindex="-1"></a>| SPX baseline (single-instrument, predecessor implementation) | +0.286 |</span>
<span id="cb1-41"><a href="#cb1-41" aria-hidden="true" tabindex="-1"></a>| **Δ vs SPX baseline** | **+0.085** ✓ |</span>
<span id="cb1-42"><a href="#cb1-42" aria-hidden="true" tabindex="-1"></a>| Risk-free baseline (avg IRX 2018-2024) | 2.33% |</span>
<span id="cb1-43"><a href="#cb1-43" aria-hidden="true" tabindex="-1"></a>| Annualized return (geometric) | +2.41% |</span>
<span id="cb1-44"><a href="#cb1-44" aria-hidden="true" tabindex="-1"></a>| Annualized volatility | 0.21% (with ML) / 0.23% (without) |</span>
<span id="cb1-45"><a href="#cb1-45" aria-hidden="true" tabindex="-1"></a>| Max drawdown over OOS (7 years) | **-0.12%** (with ML) / -0.13% (without) |</span>
<span id="cb1-46"><a href="#cb1-46" aria-hidden="true" tabindex="-1"></a>| Trades total (sum across 4 instruments) | 437 |</span>
<span id="cb1-47"><a href="#cb1-47" aria-hidden="true" tabindex="-1"></a>| OOS span | 2018-01-01 → 2024-12-31 (1,760 trading days) |</span>
<span id="cb1-48"><a href="#cb1-48" aria-hidden="true" tabindex="-1"></a>| ML overlay | Regime-stress scaler <span class="in">`(1 − p_stress)`</span> applied to daily book exposure |</span>
<span id="cb1-49"><a href="#cb1-49" aria-hidden="true" tabindex="-1"></a>| ML acceptance gate | Brier-score reduction +14.1% vs naive baseline (gate at ≥5%) ✓ |</span>
<span id="cb1-50"><a href="#cb1-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-51"><a href="#cb1-51" aria-hidden="true" tabindex="-1"></a><span class="fu">### Multiple-testing validation</span></span>
<span id="cb1-52"><a href="#cb1-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-53"><a href="#cb1-53" aria-hidden="true" tabindex="-1"></a>The basket was selected from a tested universe of 12 instruments (3 ETFs: SPX, TLT, GLD; 9 single-stocks: AAPL, MSFT, GOOGL, JNJ, KO, PG, WMT, JPM, PEP). Selection bias is corrected via DSR + PBO:</span>
<span id="cb1-54"><a href="#cb1-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-55"><a href="#cb1-55" aria-hidden="true" tabindex="-1"></a>| Correction | Value | Acceptance | Pass? |</span>
<span id="cb1-56"><a href="#cb1-56" aria-hidden="true" tabindex="-1"></a>|---|---:|---|:-:|</span>
<span id="cb1-57"><a href="#cb1-57" aria-hidden="true" tabindex="-1"></a>| Raw trials tested (N) | 12 | informational | n/a |</span>
<span id="cb1-58"><a href="#cb1-58" aria-hidden="true" tabindex="-1"></a>| Avg pairwise return correlation (ρ̄) | 0.261 | informational | n/a |</span>
<span id="cb1-59"><a href="#cb1-59" aria-hidden="true" tabindex="-1"></a>| Implied independent trials (N̂)  | 9 | informational | n/a |</span>
<span id="cb1-60"><a href="#cb1-60" aria-hidden="true" tabindex="-1"></a>| Deflated Sharpe (PSR) | 1.0000 | ≥ 0.95 | ✓ |</span>
<span id="cb1-61"><a href="#cb1-61" aria-hidden="true" tabindex="-1"></a>| PBO via CSCV (S=16, 12,870 logits) | 0.0402 | ≤ 0.30 | ✓ |</span>
<span id="cb1-62"><a href="#cb1-62" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-63"><a href="#cb1-63" aria-hidden="true" tabindex="-1"></a>Both gates pass. The headline is statistically significant after correction for the 12-trial selection.</span>
<span id="cb1-64"><a href="#cb1-64" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-65"><a href="#cb1-65" aria-hidden="true" tabindex="-1"></a><span class="fu">### Equity curve</span></span>
<span id="cb1-66"><a href="#cb1-66" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-67"><a href="#cb1-67" aria-hidden="true" tabindex="-1"></a><span class="in">```{=html}</span></span>
<span id="cb1-68"><a href="#cb1-68" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;iframe src="charts/equity_headline_vs_anchor.html" width="100%" height="560" frameborder="0"&gt;&lt;/iframe&gt;</span></span>
<span id="cb1-69"><a href="#cb1-69" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-70"><a href="#cb1-70" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-71"><a href="#cb1-71" aria-hidden="true" tabindex="-1"></a>The headline ends at 1.18× starting equity over 7 years (CAGR 2.41%). The SPX baseline (Sharpe 0.286, ann_ret 2.49%) ends very close in absolute terms. The Sharpe advantage (+0.085 with the ML overlay engaged) shows up not in absolute return but in volatility: the headline runs at 0.21% annualized volatility versus the SPX baseline's 0.55%, so the same return is more risk-efficient.</span>
<span id="cb1-72"><a href="#cb1-72" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-73"><a href="#cb1-73" aria-hidden="true" tabindex="-1"></a><span class="fu">### Drawdown</span></span>
<span id="cb1-74"><a href="#cb1-74" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-75"><a href="#cb1-75" aria-hidden="true" tabindex="-1"></a><span class="in">```{=html}</span></span>
<span id="cb1-76"><a href="#cb1-76" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;iframe src="charts/drawdown_headline.html" width="100%" height="460" frameborder="0"&gt;&lt;/iframe&gt;</span></span>
<span id="cb1-77"><a href="#cb1-77" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-78"><a href="#cb1-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-79"><a href="#cb1-79" aria-hidden="true" tabindex="-1"></a>Maximum drawdown of -0.13% over the 7-year OOS sample. The defined-risk put-credit-spread structure plus the halt framework absorbs every named stress event without measurable equity damage.</span>
<span id="cb1-80"><a href="#cb1-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-81"><a href="#cb1-81" aria-hidden="true" tabindex="-1"></a><span class="fu">### Per-instrument breakdown</span></span>
<span id="cb1-82"><a href="#cb1-82" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-83"><a href="#cb1-83" aria-hidden="true" tabindex="-1"></a>| Ticker | Sharpe (excess) | n_trades | Win rate | Max DD | Ann. return | Final $ (from $50K start) |</span>
<span id="cb1-84"><a href="#cb1-84" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|---:|---:|---:|---:|</span>
<span id="cb1-85"><a href="#cb1-85" aria-hidden="true" tabindex="-1"></a>| AAPL | +0.264 | 112 | 74.1% | -0.50% | +2.44% | $59,170 |</span>
<span id="cb1-86"><a href="#cb1-86" aria-hidden="true" tabindex="-1"></a>| MSFT | +0.269 | 112 | 73.2% | -0.37% | +2.42% | $59,124 |</span>
<span id="cb1-87"><a href="#cb1-87" aria-hidden="true" tabindex="-1"></a>| WMT  | +0.263 | 107 | 69.2% | -0.18% | +2.40% | $59,017 |</span>
<span id="cb1-88"><a href="#cb1-88" aria-hidden="true" tabindex="-1"></a>| GLD  | +0.138 | 106 | 75.5% | -0.23% | +2.40% | $59,008 |</span>
<span id="cb1-89"><a href="#cb1-89" aria-hidden="true" tabindex="-1"></a>| **Aggregate (equal-weight 4)** | **+0.359** | 437 | 73.0% | **-0.13%** | +2.41% | $231,313 |</span>
<span id="cb1-90"><a href="#cb1-90" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-91"><a href="#cb1-91" aria-hidden="true" tabindex="-1"></a>The book aggregate has higher Sharpe than the per-instrument average because cross-instrument correlation is low (mean pairwise 0.26), so equal-weighting reduces volatility without proportional return loss.</span>
<span id="cb1-92"><a href="#cb1-92" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-93"><a href="#cb1-93" aria-hidden="true" tabindex="-1"></a><span class="in">```{=html}</span></span>
<span id="cb1-94"><a href="#cb1-94" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;iframe src="charts/per_instrument_sharpe.html" width="100%" height="490" frameborder="0"&gt;&lt;/iframe&gt;</span></span>
<span id="cb1-95"><a href="#cb1-95" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-96"><a href="#cb1-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-97"><a href="#cb1-97" aria-hidden="true" tabindex="-1"></a><span class="fu">## Anchor comparison vs SPX baseline</span></span>
<span id="cb1-98"><a href="#cb1-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-99"><a href="#cb1-99" aria-hidden="true" tabindex="-1"></a>| Strategy | Architecture | Sharpe (excess) | Trades | OOS window |</span>
<span id="cb1-100"><a href="#cb1-100" aria-hidden="true" tabindex="-1"></a>|---|---|---:|---:|---|</span>
<span id="cb1-101"><a href="#cb1-101" aria-hidden="true" tabindex="-1"></a>| SPX baseline (predecessor implementation, historical reference) | SPX put-only with halts engaged | +0.286 | 210 | 2018–2024 |</span>
<span id="cb1-102"><a href="#cb1-102" aria-hidden="true" tabindex="-1"></a>| **Headline** | **4-instrument basket, put-only, halts engaged, regime-stress ML overlay** | **+0.371** | 437 | 2018–2024 |</span>
<span id="cb1-103"><a href="#cb1-103" aria-hidden="true" tabindex="-1"></a>| **Δ vs SPX baseline** | (same OOS window, both halts engaged put-only) | **+0.085** | +227 | 2018–2024 |</span>
<span id="cb1-104"><a href="#cb1-104" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-105"><a href="#cb1-105" aria-hidden="true" tabindex="-1"></a>The new headline beats the SPX baseline on excess Sharpe, with roughly 2× the trade sample, comparable max drawdown, and cross-asset diversification (equity + commodity) the baseline lacks. The SPX baseline (the predecessor implementation) is included as a historical reference; reproducing its exact equity curve is not supported on the current engine version because the engine has materially evolved since the baseline was recorded.</span>
<span id="cb1-106"><a href="#cb1-106" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-107"><a href="#cb1-107" aria-hidden="true" tabindex="-1"></a><span class="fu">## Variants tested: alternative baskets</span></span>
<span id="cb1-108"><a href="#cb1-108" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-109"><a href="#cb1-109" aria-hidden="true" tabindex="-1"></a>All baskets below are run with halts engaged, equal-weighted at $50,000 per instrument. None were selected as headline; they are shown to demonstrate what the headline is being chosen against.</span>
<span id="cb1-110"><a href="#cb1-110" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-111"><a href="#cb1-111" aria-hidden="true" tabindex="-1"></a>| Basket | n_inst | Sharpe (excess) | AnnRet | AnnVol | MaxDD | Δ vs SPX baseline (+0.286) |</span>
<span id="cb1-112"><a href="#cb1-112" aria-hidden="true" tabindex="-1"></a>|---|:-:|---:|---:|---:|---:|---:|</span>
<span id="cb1-113"><a href="#cb1-113" aria-hidden="true" tabindex="-1"></a>| (A) SPX put-only alone | 1 | -0.347 | +2.04% | 0.84% | -0.78% | -0.633 |</span>
<span id="cb1-114"><a href="#cb1-114" aria-hidden="true" tabindex="-1"></a>| (B) 3-name basket (AAPL+MSFT+WMT) | 3 | +0.350 | +2.42% | 0.26% | -0.19% | +0.064 |</span>
<span id="cb1-115"><a href="#cb1-115" aria-hidden="true" tabindex="-1"></a>| (C) 3-ETF basket (SPX + TLT + GLD put-only) | 3 | -0.312 | +2.22% | 0.35% | -0.31% | -0.598 |</span>
<span id="cb1-116"><a href="#cb1-116" aria-hidden="true" tabindex="-1"></a>| **(D) the 4-instrument basket ← HEADLINE** | **4** | **+0.359** | **+2.41%** | **0.23%** | **-0.13%** | **+0.073** |</span>
<span id="cb1-117"><a href="#cb1-117" aria-hidden="true" tabindex="-1"></a>| (E) Full 6-instrument book (3-ETF basket + 3-name basket) | 6 | -0.036 | +2.32% | 0.26% | -0.17% | -0.322 |</span>
<span id="cb1-118"><a href="#cb1-118" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-119"><a href="#cb1-119" aria-hidden="true" tabindex="-1"></a>Pattern: adding SPX or TLT to the headline drags the Sharpe down because their individual put-credit-spread excess Sharpes are negative (-0.35 and -0.43 respectively over OOS). The cross-asset diversification benefit of including GLD (which is barely positive on its own) outweighs the volatility-reduction cost. Adding more drag-instruments (SPX, TLT) does not produce a net benefit.</span>
<span id="cb1-120"><a href="#cb1-120" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-121"><a href="#cb1-121" aria-hidden="true" tabindex="-1"></a><span class="fu">## Variants tested: iron condor architecture</span></span>
<span id="cb1-122"><a href="#cb1-122" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-123"><a href="#cb1-123" aria-hidden="true" tabindex="-1"></a>We tested both architectures on the same engine and underlying universe. Iron condor (put + call wings on the same expiry) underperforms put-only across every comparable comparison in OOS 2018-2024:</span>
<span id="cb1-124"><a href="#cb1-124" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-125"><a href="#cb1-125" aria-hidden="true" tabindex="-1"></a>| Mode | Universe | Sharpe (excess) | Δ vs SPX baseline | Notes |</span>
<span id="cb1-126"><a href="#cb1-126" aria-hidden="true" tabindex="-1"></a>|---|---|---:|---:|---|</span>
<span id="cb1-127"><a href="#cb1-127" aria-hidden="true" tabindex="-1"></a>| Iron condor, SPX only | 1 inst | -1.882 | -2.168 | Call wing destroyed by post-2020 SPX rally |</span>
<span id="cb1-128"><a href="#cb1-128" aria-hidden="true" tabindex="-1"></a>| Iron condor, 3-instrument cluster | SPX/TLT/GLD | -2.292 | -2.578 | Same pattern across all three IC instruments |</span>
<span id="cb1-129"><a href="#cb1-129" aria-hidden="true" tabindex="-1"></a>| Put-only, SPX | 1 inst | -0.347 | -0.633 | Same engine, IC removed |</span>
<span id="cb1-130"><a href="#cb1-130" aria-hidden="true" tabindex="-1"></a>| Put-only, 3-instrument cluster | SPX/TLT/GLD | -0.369 | -0.655 | Same engine, IC removed |</span>
<span id="cb1-131"><a href="#cb1-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-132"><a href="#cb1-132" aria-hidden="true" tabindex="-1"></a>Iron condor underperforms put-only in every comparison. The call-wing leg of the iron condor systematically lost in 2018-2024 due to the trending equity-index regime. Reported as a tested extension that did not add value, not as the headline.</span>
<span id="cb1-133"><a href="#cb1-133" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-134"><a href="#cb1-134" aria-hidden="true" tabindex="-1"></a><span class="fu">## Halts engaged vs disengaged</span></span>
<span id="cb1-135"><a href="#cb1-135" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-136"><a href="#cb1-136" aria-hidden="true" tabindex="-1"></a>Demonstrates that the halt framework is doing real work, every instrument has higher Sharpe (excess) when halts are active vs naked.</span>
<span id="cb1-137"><a href="#cb1-137" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-138"><a href="#cb1-138" aria-hidden="true" tabindex="-1"></a>| Ticker | Sharpe with halts disengaged | Halts Sharpe | Δ from halts |</span>
<span id="cb1-139"><a href="#cb1-139" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|---:|</span>
<span id="cb1-140"><a href="#cb1-140" aria-hidden="true" tabindex="-1"></a>| AAPL | +0.155 | +0.264 | +0.109 |</span>
<span id="cb1-141"><a href="#cb1-141" aria-hidden="true" tabindex="-1"></a>| MSFT | +0.037 | +0.269 | +0.232 |</span>
<span id="cb1-142"><a href="#cb1-142" aria-hidden="true" tabindex="-1"></a>| WMT  | +0.063 | +0.263 | +0.200 |</span>
<span id="cb1-143"><a href="#cb1-143" aria-hidden="true" tabindex="-1"></a>| GLD  | -0.971 | +0.138 | +1.109 |</span>
<span id="cb1-144"><a href="#cb1-144" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-145"><a href="#cb1-145" aria-hidden="true" tabindex="-1"></a>The halt framework's contribution is measurable per instrument and consistently positive. GLD has the largest gap because its naked exposure is fully on through every regime; the halt framework gates the worst stretches.</span>
<span id="cb1-146"><a href="#cb1-146" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-147"><a href="#cb1-147" aria-hidden="true" tabindex="-1"></a><span class="fu">## Stress-event behavior</span></span>
<span id="cb1-148"><a href="#cb1-148" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-149"><a href="#cb1-149" aria-hidden="true" tabindex="-1"></a>Computed on the headline basket equity curve, halts engaged, equal-weight $50K per instrument (basket starting equity $200K). Drawdown is peak-to-trough WITHIN each window using a running cumulative max.</span>
<span id="cb1-150"><a href="#cb1-150" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-151"><a href="#cb1-151" aria-hidden="true" tabindex="-1"></a>| Event | Window probed | Net P&amp;L | Peak-to-trough DD | Trough date |</span>
<span id="cb1-152"><a href="#cb1-152" aria-hidden="true" tabindex="-1"></a>|---|---|---:|---:|---|</span>
<span id="cb1-153"><a href="#cb1-153" aria-hidden="true" tabindex="-1"></a>| Volmageddon | 2018-01-22 → 2018-02-16 | -$35 | **-0.099%** | 2018-02-07 |</span>
<span id="cb1-154"><a href="#cb1-154" aria-hidden="true" tabindex="-1"></a>| Q4 2018 selloff | 2018-11-26 → 2019-01-24 | +$783 | 0.000% | (curve monotonic up) |</span>
<span id="cb1-155"><a href="#cb1-155" aria-hidden="true" tabindex="-1"></a>| COVID crash | 2020-02-24 → 2020-04-23 | +$102 | 0.000% | (curve monotonic up) |</span>
<span id="cb1-156"><a href="#cb1-156" aria-hidden="true" tabindex="-1"></a>| 2022 bear market | 2022-01-03 → 2022-12-30 | +$4,223 | 0.000% | (curve monotonic up) |</span>
<span id="cb1-157"><a href="#cb1-157" aria-hidden="true" tabindex="-1"></a>| Banking crisis | 2023-02-13 → 2023-04-13 | +$1,652 | 0.000% | (curve monotonic up) |</span>
<span id="cb1-158"><a href="#cb1-158" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-159"><a href="#cb1-159" aria-hidden="true" tabindex="-1"></a>The 0.000% peak-to-trough entries are not measurement error. They reflect a structural feature of the halt-gated put-credit-spread architecture: during these stress windows the halt framework reduced or paused new entries, the open positions either expired profitably or hit stop-loss within their wing-width bound, and the unutilized capital continued earning the realized T-bill rate. Net trading P&amp;L plus cash carry was positive on every trading day through these windows, so the equity curve never made a new low.</span>
<span id="cb1-160"><a href="#cb1-160" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-161"><a href="#cb1-161" aria-hidden="true" tabindex="-1"></a>Volmageddon is the one exception. The early-2018 timing meant the basket was fully deployed when the VIX spike hit, and the resulting -$35 net P&amp;L (-0.099% peak-to-trough) is the largest intra-event dip the strategy registered across all five named events.</span>
<span id="cb1-162"><a href="#cb1-162" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-163"><a href="#cb1-163" aria-hidden="true" tabindex="-1"></a><span class="fu">## Trade fates and rates</span></span>
<span id="cb1-164"><a href="#cb1-164" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-165"><a href="#cb1-165" aria-hidden="true" tabindex="-1"></a>Every trade exits one of five fates. The distribution across the 437-trade headline blotter:</span>
<span id="cb1-166"><a href="#cb1-166" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-167"><a href="#cb1-167" aria-hidden="true" tabindex="-1"></a>| Fate | Trigger | Count | % of trades |</span>
<span id="cb1-168"><a href="#cb1-168" aria-hidden="true" tabindex="-1"></a>|---|---|---:|---:|</span>
<span id="cb1-169"><a href="#cb1-169" aria-hidden="true" tabindex="-1"></a>| <span class="in">`profit_target`</span> | Exit debit ≤ 50% of entry credit | 280 | **64.1%** |</span>
<span id="cb1-170"><a href="#cb1-170" aria-hidden="true" tabindex="-1"></a>| <span class="in">`stop_loss`</span> | Exit debit ≥ 200% of entry credit (gap-aware fill) | 81 | 18.5% |</span>
<span id="cb1-171"><a href="#cb1-171" aria-hidden="true" tabindex="-1"></a>| <span class="in">`time_exit`</span> | DTE ≤ 21 | 75 | 17.2% |</span>
<span id="cb1-172"><a href="#cb1-172" aria-hidden="true" tabindex="-1"></a>| <span class="in">`emergency`</span> | \|short_delta\| &gt; 0.50 | 1 | 0.2% |</span>
<span id="cb1-173"><a href="#cb1-173" aria-hidden="true" tabindex="-1"></a>| <span class="in">`eos_force`</span> | End-of-OOS forced close | 0 | 0.0% |</span>
<span id="cb1-174"><a href="#cb1-174" aria-hidden="true" tabindex="-1"></a>| **Total** | | **437** | 100% |</span>
<span id="cb1-175"><a href="#cb1-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-176"><a href="#cb1-176" aria-hidden="true" tabindex="-1"></a>Reading the rates the rubric asks for:</span>
<span id="cb1-177"><a href="#cb1-177" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-178"><a href="#cb1-178" aria-hidden="true" tabindex="-1"></a>| Rate | Value |</span>
<span id="cb1-179"><a href="#cb1-179" aria-hidden="true" tabindex="-1"></a>|---|---:|</span>
<span id="cb1-180"><a href="#cb1-180" aria-hidden="true" tabindex="-1"></a>| **Success rate** (P&amp;L &gt; 0) | **73.0%** |</span>
<span id="cb1-181"><a href="#cb1-181" aria-hidden="true" tabindex="-1"></a>| **Stop-loss rate** | 18.5% |</span>
<span id="cb1-182"><a href="#cb1-182" aria-hidden="true" tabindex="-1"></a>| **Timeout rate** (<span class="in">`time_exit`</span>) | 17.2% |</span>
<span id="cb1-183"><a href="#cb1-183" aria-hidden="true" tabindex="-1"></a>| **Emergency-exit rate** | 0.2% |</span>
<span id="cb1-184"><a href="#cb1-184" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-185"><a href="#cb1-185" aria-hidden="true" tabindex="-1"></a><span class="fu">## Per-trade summary statistics</span></span>
<span id="cb1-186"><a href="#cb1-186" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-187"><a href="#cb1-187" aria-hidden="true" tabindex="-1"></a>| Metric | Value |</span>
<span id="cb1-188"><a href="#cb1-188" aria-hidden="true" tabindex="-1"></a>|---|---:|</span>
<span id="cb1-189"><a href="#cb1-189" aria-hidden="true" tabindex="-1"></a>| Total trades | 437 |</span>
<span id="cb1-190"><a href="#cb1-190" aria-hidden="true" tabindex="-1"></a>| Winning trades | 319 |</span>
<span id="cb1-191"><a href="#cb1-191" aria-hidden="true" tabindex="-1"></a>| Losing trades | 118 |</span>
<span id="cb1-192"><a href="#cb1-192" aria-hidden="true" tabindex="-1"></a>| Mean P&amp;L per spread | +$3.42 |</span>
<span id="cb1-193"><a href="#cb1-193" aria-hidden="true" tabindex="-1"></a>| Median P&amp;L per spread | +$17.85 |</span>
<span id="cb1-194"><a href="#cb1-194" aria-hidden="true" tabindex="-1"></a>| Standard deviation of P&amp;L | $37.66 |</span>
<span id="cb1-195"><a href="#cb1-195" aria-hidden="true" tabindex="-1"></a>| Largest single win | +$49.50 |</span>
<span id="cb1-196"><a href="#cb1-196" aria-hidden="true" tabindex="-1"></a>| Largest single loss | -$186.00 |</span>
<span id="cb1-197"><a href="#cb1-197" aria-hidden="true" tabindex="-1"></a>| Mean trade return | +8.25% |</span>
<span id="cb1-198"><a href="#cb1-198" aria-hidden="true" tabindex="-1"></a>| Mean trade lifetime | 6.5 days |</span>
<span id="cb1-199"><a href="#cb1-199" aria-hidden="true" tabindex="-1"></a>| Median trade lifetime | 7 days |</span>
<span id="cb1-200"><a href="#cb1-200" aria-hidden="true" tabindex="-1"></a>| Profit factor (gross win / gross loss) | 1.26 |</span>
<span id="cb1-201"><a href="#cb1-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-202"><a href="#cb1-202" aria-hidden="true" tabindex="-1"></a>The 6.5-day mean lifetime reflects how the strategy actually deploys capital: profit-target exits fire quickly in calm regimes, and the basket spends most of its capital sitting on T-bill carry between trade cycles. Median holding period is 7 days; the 25th-to-75th percentile window is 3 to 10 days; no trade exceeds 14 days because the time-exit rule forces a close at DTE ≤ 21 against the 30-45 DTE entry window.</span>
<span id="cb1-203"><a href="#cb1-203" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-204"><a href="#cb1-204" aria-hidden="true" tabindex="-1"></a><span class="fu">## Per-instrument breakdown</span></span>
<span id="cb1-205"><a href="#cb1-205" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-206"><a href="#cb1-206" aria-hidden="true" tabindex="-1"></a>| Ticker | Trades | Wins | Win rate | Mean P&amp;L | Total P&amp;L |</span>
<span id="cb1-207"><a href="#cb1-207" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|---:|---:|---:|</span>
<span id="cb1-208"><a href="#cb1-208" aria-hidden="true" tabindex="-1"></a>| AAPL | 112 | 83 | 74.1% | +$4.11 | +$460.23 |</span>
<span id="cb1-209"><a href="#cb1-209" aria-hidden="true" tabindex="-1"></a>| MSFT | 112 | 82 | 73.2% | +$3.54 | +$396.33 |</span>
<span id="cb1-210"><a href="#cb1-210" aria-hidden="true" tabindex="-1"></a>| GLD  | 106 | 80 | 75.5% | +$3.06 | +$324.70 |</span>
<span id="cb1-211"><a href="#cb1-211" aria-hidden="true" tabindex="-1"></a>| WMT  | 107 | 74 | 69.2% | +$2.92 | +$312.87 |</span>
<span id="cb1-212"><a href="#cb1-212" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-213"><a href="#cb1-213" aria-hidden="true" tabindex="-1"></a><span class="fu">## P&amp;L per trade across OOS</span></span>
<span id="cb1-214"><a href="#cb1-214" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-215"><a href="#cb1-215" aria-hidden="true" tabindex="-1"></a><span class="in">```{=html}</span></span>
<span id="cb1-216"><a href="#cb1-216" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;iframe src="charts/pnl_per_trade.html" width="100%" height="510" frameborder="0"&gt;&lt;/iframe&gt;</span></span>
<span id="cb1-217"><a href="#cb1-217" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-218"><a href="#cb1-218" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-219"><a href="#cb1-219" aria-hidden="true" tabindex="-1"></a><span class="fu">## Trade-return distribution</span></span>
<span id="cb1-220"><a href="#cb1-220" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-221"><a href="#cb1-221" aria-hidden="true" tabindex="-1"></a><span class="in">```{=html}</span></span>
<span id="cb1-222"><a href="#cb1-222" aria-hidden="true" tabindex="-1"></a><span class="in">&lt;iframe src="charts/trade_return_distribution.html" width="100%" height="490" frameborder="0"&gt;&lt;/iframe&gt;</span></span>
<span id="cb1-223"><a href="#cb1-223" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb1-224"><a href="#cb1-224" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-225"><a href="#cb1-225" aria-hidden="true" tabindex="-1"></a>The distribution is right-skewed by design: a 16-delta short put expires worthless ~84% of the time under lognormal assumptions, and <span class="in">`profit_target`</span> closes wins early at 50% of credit. Losses are bounded by the wing-width stop. The 1.26 profit factor reflects mean-reversion of variance to the realized, not directional alpha on the underlying.</span>
<span id="cb1-226"><a href="#cb1-226" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-227"><a href="#cb1-227" aria-hidden="true" tabindex="-1"></a><span class="fu">## Ledger (monthly P&amp;L sample)</span></span>
<span id="cb1-228"><a href="#cb1-228" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-229"><a href="#cb1-229" aria-hidden="true" tabindex="-1"></a>| Month | Trades closed | Net P&amp;L | Cumulative P&amp;L |</span>
<span id="cb1-230"><a href="#cb1-230" aria-hidden="true" tabindex="-1"></a>|---|---:|---:|---:|</span>
<span id="cb1-231"><a href="#cb1-231" aria-hidden="true" tabindex="-1"></a>| 2018-01 | 7 | +$36.75 | +$36.75 |</span>
<span id="cb1-232"><a href="#cb1-232" aria-hidden="true" tabindex="-1"></a>| 2018-02 | 5 | -$193.88 | -$157.13 |</span>
<span id="cb1-233"><a href="#cb1-233" aria-hidden="true" tabindex="-1"></a>| 2018-05 | 9 | +$97.05 | -$60.08 |</span>
<span id="cb1-234"><a href="#cb1-234" aria-hidden="true" tabindex="-1"></a>| 2018-08 | 17 | +$191.15 | +$179.58 |</span>
<span id="cb1-235"><a href="#cb1-235" aria-hidden="true" tabindex="-1"></a>| 2018-09 | 12 | +$175.50 | +$355.08 |</span>
<span id="cb1-236"><a href="#cb1-236" aria-hidden="true" tabindex="-1"></a>| 2018-10 | 11 | -$290.25 | +$64.83 |</span>
<span id="cb1-237"><a href="#cb1-237" aria-hidden="true" tabindex="-1"></a>| 2019-07 | 19 | +$315.85 | +$369.58 |</span>
<span id="cb1-238"><a href="#cb1-238" aria-hidden="true" tabindex="-1"></a>| 2019-12 | 18 | +$321.70 | +$529.38 |</span>
<span id="cb1-239"><a href="#cb1-239" aria-hidden="true" tabindex="-1"></a>| 2020-03 | 14 | -$11.20 | +$612.10 |</span>
<span id="cb1-240"><a href="#cb1-240" aria-hidden="true" tabindex="-1"></a>| ... | ... | ... | ... |</span>
<span id="cb1-241"><a href="#cb1-241" aria-hidden="true" tabindex="-1"></a>| 2024-08 | 5 | -$361.65 | +$1,237.08 |</span>
<span id="cb1-242"><a href="#cb1-242" aria-hidden="true" tabindex="-1"></a>| 2024-11 | 12 | +$181.80 | +$1,418.88 |</span>
<span id="cb1-243"><a href="#cb1-243" aria-hidden="true" tabindex="-1"></a>| 2024-12 | 12 | +$75.25 | +$1,494.13 |</span>
<span id="cb1-244"><a href="#cb1-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-245"><a href="#cb1-245" aria-hidden="true" tabindex="-1"></a>*Showing 12 of 84 months from January 2018 to December 2024. Net P&amp;L in dollars per spread (per-contract basis at $100 multiplier). The full 84-month ledger and the 437-row blotter are at `website/data/blotter.json`.*</span>
<span id="cb1-246"><a href="#cb1-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-247"><a href="#cb1-247" aria-hidden="true" tabindex="-1"></a><span class="fu">## Blotter</span></span>
<span id="cb1-248"><a href="#cb1-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-249"><a href="#cb1-249" aria-hidden="true" tabindex="-1"></a>Random sample of 10 trades from the 437-row blotter (seed=42).</span>
<span id="cb1-250"><a href="#cb1-250" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-251"><a href="#cb1-251" aria-hidden="true" tabindex="-1"></a>| trd_prd | Entry | Exit | Ticker | Side | Qty | Entry credit | Exit debit | Fate | P&amp;L | Return % | Success |</span>
<span id="cb1-252"><a href="#cb1-252" aria-hidden="true" tabindex="-1"></a>|---|---|---|:-:|:-:|---:|---:|---:|---|---:|---:|:-:|</span>
<span id="cb1-253"><a href="#cb1-253" aria-hidden="true" tabindex="-1"></a>| 2018.19 | 2018-05-07 | 2018-05-16 | WMT | P | 1 | $22.45 | $0.90 | profit_target | $+21.55 | +96.0% | True |</span>
<span id="cb1-254"><a href="#cb1-254" aria-hidden="true" tabindex="-1"></a>| 2018.39 | 2018-09-24 | 2018-10-05 | WMT | P | 1 | $35.80 | $60.55 | time_exit | $-24.75 | -69.1% | False |</span>
<span id="cb1-255"><a href="#cb1-255" aria-hidden="true" tabindex="-1"></a>| 2018.40 | 2018-10-01 | 2018-10-11 | GLD | P | 1 | $15.05 | $4.50 | profit_target | $+10.55 | +70.1% | True |</span>
<span id="cb1-256"><a href="#cb1-256" aria-hidden="true" tabindex="-1"></a>| 2019.07 | 2019-02-11 | 2019-02-15 | MSFT | P | 1 | $38.70 | $15.30 | profit_target | $+23.40 | +60.5% | True |</span>
<span id="cb1-257"><a href="#cb1-257" aria-hidden="true" tabindex="-1"></a>| 2019.30 | 2019-07-22 | 2019-08-01 | WMT | P | 1 | $38.85 | $88.55 | stop_loss | $-49.70 | -127.9% | False |</span>
<span id="cb1-258"><a href="#cb1-258" aria-hidden="true" tabindex="-1"></a>| 2019.48 | 2019-11-25 | 2019-12-04 | WMT | P | 1 | $29.85 | $17.75 | profit_target | $+12.10 | +40.5% | True |</span>
<span id="cb1-259"><a href="#cb1-259" aria-hidden="true" tabindex="-1"></a>| 2019.52 | 2019-12-23 | 2019-12-26 | GLD | P | 1 | $19.70 | $9.95 | profit_target | $+9.75 | +49.5% | True |</span>
<span id="cb1-260"><a href="#cb1-260" aria-hidden="true" tabindex="-1"></a>| 2024.07 | 2024-02-12 | 2024-02-23 | MSFT | P | 1 | $52.80 | $34.25 | time_exit | $+18.55 | +35.1% | True |</span>
<span id="cb1-261"><a href="#cb1-261" aria-hidden="true" tabindex="-1"></a>| 2024.23 | 2024-06-03 | 2024-06-07 | GLD | P | 1 | $54.40 | $147.50 | stop_loss | $-93.10 | -171.1% | False |</span>
<span id="cb1-262"><a href="#cb1-262" aria-hidden="true" tabindex="-1"></a>| 2024.23 | 2024-06-03 | 2024-06-05 | WMT | P | 1 | $14.45 | $6.20 | profit_target | $+8.25 | +57.1% | True |</span>
<span id="cb1-263"><a href="#cb1-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-264"><a href="#cb1-264" aria-hidden="true" tabindex="-1"></a>The <span class="in">`trd_prd`</span> index encodes year + ISO week as a single decimal. Entries on the same Monday share the same <span class="in">`trd_prd`</span>.</span>
<span id="cb1-265"><a href="#cb1-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-266"><a href="#cb1-266" aria-hidden="true" tabindex="-1"></a>*Showing 10 of 437 trades. Full blotter at `website/data/blotter.json`.*</span>
<span id="cb1-267"><a href="#cb1-267" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-268"><a href="#cb1-268" aria-hidden="true" tabindex="-1"></a><span class="fu">## How will you know the strategy is performing as expected?</span></span>
<span id="cb1-269"><a href="#cb1-269" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-270"><a href="#cb1-270" aria-hidden="true" tabindex="-1"></a>A rolling 60-trade window of the realized win rate is compared against the OOS baseline of μ = 0.730. The Hoeffding inequality bounds the probability that observed underperformance is due to chance: while the bound stays at or above 50%, the strategy is operating within its modeled regime and trading continues at full size. Backtested over the 2018-2024 OOS sample, the bound was at or above 50% on 88% of post-warmup trades.</span>
<span id="cb1-271"><a href="#cb1-271" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-272"><a href="#cb1-272" aria-hidden="true" tabindex="-1"></a><span class="fu">## How will you quantify when the strategy stops working?</span></span>
<span id="cb1-273"><a href="#cb1-273" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-274"><a href="#cb1-274" aria-hidden="true" tabindex="-1"></a>The same Hoeffding bound. When the bound drops below 25% the position size is cut, when it drops below 10% entries are halted entirely and the strategy is reviewed. The thresholds are pre-set, distribution-free, and apply uniformly across the 4-instrument basket. The OOS sample produced no critical signal across 1,760 trading days; full bound-trace and worked example on the <span class="co">[</span><span class="ot">Live Monitoring</span><span class="co">](monitoring.qmd)</span> page.</span>
<span id="cb1-275"><a href="#cb1-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-276"><a href="#cb1-276" aria-hidden="true" tabindex="-1"></a>For the data sources behind these numbers, see <span class="co">[</span><span class="ot">Data and Sources</span><span class="co">](data_and_literature.qmd)</span>.</span></code><button title="Copy to Clipboard" class="code-copy-button" data-in-quarto-modal=""><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
<p>R &amp; M Trade Desk · Robert Lanni and Mario Treviño · FinTech 533 · Duke MEng FinTech</p>
</div>
    <div class="nav-footer-right">
      &nbsp;
    </div>
  </div>
</footer>




</body></html>